use std::fs;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn assert_file_contains(path: PathBuf, needle: &str) {
    let source = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} should be readable: {error}", path.display()));
    assert!(
        source.contains(needle),
        "{} should contain {:?}",
        path.display(),
        needle
    );
}

fn assert_file_does_not_contain(path: PathBuf, needle: &str) {
    let source = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} should be readable: {error}", path.display()));
    assert!(
        !source.contains(needle),
        "{} should not contain {:?}",
        path.display(),
        needle
    );
}

fn assert_file_contains_ci(path: PathBuf, needle: &str) {
    let source = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} should be readable: {error}", path.display()));
    assert!(
        source.to_lowercase().contains(&needle.to_lowercase()),
        "{} should contain {:?} case-insensitively",
        path.display(),
        needle
    );
}

fn assert_file_does_not_contain_ci(path: PathBuf, needle: &str) {
    let source = fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{} should be readable: {error}", path.display()));
    assert!(
        !source.to_lowercase().contains(&needle.to_lowercase()),
        "{} should not contain {:?} case-insensitively",
        path.display(),
        needle
    );
}

fn plan_execution_prompt_command(command_parts: &[&str]) -> String {
    format!(
        "run `featureforge plan execution {}",
        command_parts.concat()
    )
}

#[test]
fn review_skill_docs_keep_final_review_dedicated_and_gate_aware() {
    let root = repo_root();

    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "final cross-task review gate",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "featureforge:requesting-code-review",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "dedicated fresh-context reviewer independent of the implementation context",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "Keep review artifacts runtime-owned:",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Review Stage: featureforge:requesting-code-review",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Reviewer Provenance: dedicated-independent",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Reviewer Source` and `Reviewer ID`",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Distinct From Stages` including both `featureforge:executing-plans` and `featureforge:subagent-driven-development`",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Recorded Execution Deviations` and `Deviation Review Verdict` aligned to the execution evidence you reviewed",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Generated By: featureforge:requesting-code-review",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Source Plan`, `Source Plan Revision`, `Strategy Checkpoint Fingerprint`, `Branch`, `Repo`, `Base Branch`, `Head SHA`",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "approved plan",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "dedicated independent reviewer",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "explicitly inspect them and state whether those deviations pass final review",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Structured Review Result Metadata",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "review-result metadata for the controller to bind to runtime-owned state",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Do not create, repair, search for, or reference runtime-owned projection files",
    );
    assert_file_does_not_contain(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "receipt-ready metadata",
    );
    assert_file_does_not_contain(
        root.join("skills/requesting-code-review/code-reviewer.md"),
        "Dedicated Reviewer Receipt Contract",
    );
}

#[test]
fn reviewer_prompts_are_non_recursive_and_runtime_command_free() {
    let root = repo_root();
    let reviewer_paths = [
        root.join("agents/code-reviewer.instructions.md"),
        root.join("agents/code-reviewer.md"),
        root.join("skills/requesting-code-review/code-reviewer.md"),
        root.join("skills/plan-fidelity-review/reviewer-prompt.md"),
        root.join("skills/plan-eng-review/accelerated-reviewer-prompt.md"),
        root.join("skills/plan-ceo-review/accelerated-reviewer-prompt.md"),
        root.join("skills/subagent-driven-development/code-quality-reviewer-prompt.md"),
        root.join("skills/subagent-driven-development/spec-reviewer-prompt.md"),
    ];

    for path in reviewer_paths {
        assert_file_contains(
            path.clone(),
            "FEATUREFORGE_REVIEWER_RUNTIME_COMMANDS_ALLOWED=no",
        );
        assert_file_does_not_contain(path.clone(), "REVIEWER_RUNTIME_COMMANDS_ALLOWED: no");
        assert_file_contains_ci(path.clone(), "do not invoke FeatureForge skills");
        assert_file_contains_ci(
            path.clone(),
            "do not run `featureforge workflow` or `featureforge plan execution` commands",
        );
        assert_file_contains_ci(
            path.clone(),
            "do not dispatch `code-reviewer` or `requesting-code-review`",
        );
        assert_file_contains(path.clone(), "If required runtime context is missing");
        assert_file_contains(path.clone(), "report a blocked review");
        assert_file_does_not_contain(path.clone(), "Run `featureforge workflow");
        assert_file_does_not_contain(path.clone(), "Run `featureforge plan execution");
        for forbidden_runtime_command in [
            "run `featureforge workflow operator".to_owned(),
            plan_execution_prompt_command(&["status"]),
            plan_execution_prompt_command(&["repair", "-review-state"]),
            plan_execution_prompt_command(&["close-current-task"]),
            plan_execution_prompt_command(&["advance-late-stage"]),
            plan_execution_prompt_command(&["rebuild", "-evidence"]),
            plan_execution_prompt_command(&["reconcile", "-review-state"]),
        ] {
            assert_file_does_not_contain_ci(path.clone(), &forbidden_runtime_command);
        }
        assert_file_does_not_contain_ci(path.clone(), "receipt");
    }

    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "The controller owns any FeatureForge runtime queries before dispatch.",
    );
    assert_file_contains(
        root.join("skills/requesting-code-review/SKILL.md"),
        "FEATUREFORGE_REVIEWER_RUNTIME_COMMANDS_ALLOWED=no",
    );
    assert_file_does_not_contain(
        root.join("skills/requesting-code-review/SKILL.md"),
        "REVIEWER_RUNTIME_COMMANDS_ALLOWED: no",
    );
}

#[test]
fn codex_reviewer_agent_launch_artifact_carries_runtime_command_env_contract() {
    let root = repo_root();
    let codex_agent = root.join(".codex/agents/code-reviewer.toml");

    assert_file_contains(codex_agent.clone(), "# REVIEWER_RUNTIME_ENV_CONTRACT");
    assert_file_contains(
        codex_agent.clone(),
        "Launcher must set FEATUREFORGE_REVIEWER_RUNTIME_COMMANDS_ALLOWED = \"no\" before starting this reviewer.",
    );
    assert_file_contains(
        codex_agent.clone(),
        "FEATUREFORGE_REVIEWER_RUNTIME_COMMANDS_ALLOWED=no",
    );
    assert_file_contains(
        codex_agent.clone(),
        "If required runtime context is missing, report a blocked review",
    );
    assert_file_does_not_contain(codex_agent, "REVIEWER_RUNTIME_COMMANDS_ALLOWED: no");
}
