//! Runtime instruction review contracts integration/benchmark crate.
use std::fs;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn assert_file_contains(path: &Path, needle: &str) {
    let source = fs::read_to_string(path).unwrap_or_else(|error| {
        featureforge::abort!("{} should be readable: {error}", path.display())
    });
    assert!(
        source.contains(needle),
        "{} should contain {:?}",
        path.display(),
        needle
    );
}

#[test]
fn review_skill_docs_keep_final_review_dedicated_and_gate_aware() {
    let root = repo_root();

    assert_file_contains(
        &root.join("skills/requesting-code-review/SKILL.md"),
        "final cross-task review gate",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/SKILL.md"),
        "featureforge:requesting-code-review",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/SKILL.md"),
        "dedicated fresh-context reviewer independent of the implementation context",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/SKILL.md"),
        "Keep review artifacts runtime-owned:",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Review Stage: featureforge:requesting-code-review",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Reviewer Provenance: dedicated-independent",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Reviewer Source` and `Reviewer ID`",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Distinct From Stages` including both `featureforge:executing-plans` and `featureforge:subagent-driven-development`",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Recorded Execution Deviations` and `Deviation Review Verdict` aligned to the execution evidence you reviewed",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Generated By: featureforge:requesting-code-review",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Source Plan`, `Source Plan Revision`, `Strategy Checkpoint Fingerprint`, `Branch`, `Repo`, `Base Branch`, `Head SHA`",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "approved plan",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "dedicated independent reviewer",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "explicitly inspect them and state whether those deviations pass final review",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "Dedicated Reviewer Receipt Contract",
    );
    assert_file_contains(
        &root.join("skills/requesting-code-review/code-reviewer.md"),
        "include structured receipt-ready metadata in your response",
    );
}
