use super::*;

struct ArtifactGateValidationFailure {
    failure_class: FailureClass,
    message: String,
}

fn summary_hash_matches(summary: &str, expected_hash: &str) -> bool {
    sha256_hex(normalize_summary_content(summary).as_bytes()) == expected_hash
}

fn validate_current_branch_test_plan_candidate_for_finish(
    context: &ExecutionContext,
    test_plan_path: &Path,
    current_head: &str,
) -> Result<(), ArtifactGateValidationFailure> {
    let test_plan = parse_artifact_document(test_plan_path);
    if test_plan.title.as_deref() != Some("# Test Plan") {
        return Err(ArtifactGateValidationFailure {
            failure_class: FailureClass::QaArtifactNotFresh,
            message: String::from("The latest test-plan artifact is malformed."),
        });
    }
    if test_plan.headers.get("Generated By") != Some(&String::from("featureforge:plan-eng-review"))
    {
        return Err(ArtifactGateValidationFailure {
            failure_class: FailureClass::QaArtifactNotFresh,
            message: String::from(
                "The latest test-plan artifact was not generated by plan-eng-review.",
            ),
        });
    }
    let expected_source_plan = format!("`{}`", context.plan_rel);
    let expected_source_plan_revision = context.plan_document.plan_revision.to_string();
    let expected_branch = &context.runtime.branch_name;
    let expected_repo = &context.runtime.repo_slug;
    let head_matches = test_plan
        .headers
        .get("Head SHA")
        .is_some_and(|value| value == current_head);
    if test_plan.headers.get("Source Plan") != Some(&expected_source_plan)
        || test_plan.headers.get("Source Plan Revision") != Some(&expected_source_plan_revision)
        || test_plan.headers.get("Branch") != Some(expected_branch)
        || test_plan.headers.get("Repo") != Some(expected_repo)
        || !head_matches
    {
        let message = if !head_matches {
            "The latest test-plan artifact does not match the current HEAD."
        } else if test_plan.headers.get("Source Plan") != Some(&expected_source_plan) {
            "The latest test-plan artifact does not match the current approved plan path."
        } else if test_plan.headers.get("Source Plan Revision")
            != Some(&expected_source_plan_revision)
        {
            "The latest test-plan artifact does not match the current approved plan revision."
        } else if test_plan.headers.get("Branch") != Some(expected_branch) {
            "The latest test-plan artifact does not match the current branch."
        } else {
            "The latest test-plan artifact does not match the current repo."
        };
        return Err(ArtifactGateValidationFailure {
            failure_class: FailureClass::QaArtifactNotFresh,
            message: String::from(message),
        });
    }
    Ok(())
}

pub(crate) fn current_test_plan_artifact_path_for_qa_recording(
    context: &ExecutionContext,
) -> Result<PathBuf, JsonFailure> {
    let current_head = context.current_head_sha()?;
    let Some(authoritative_path) =
        select_authoritative_test_plan_artifact_candidate_for_qa_recording(context, &current_head)
            .map_err(|failure| JsonFailure::new(failure.failure_class, failure.message))?
    else {
        return Err(JsonFailure::new(
            FailureClass::ExecutionStateNotReady,
            "Current late-stage recording requires a current authoritative test-plan artifact for the current branch.",
        ));
    };
    Ok(authoritative_path)
}

fn select_authoritative_test_plan_artifact_candidate_for_qa_recording(
    context: &ExecutionContext,
    current_head: &str,
) -> Result<Option<PathBuf>, ArtifactGateValidationFailure> {
    let artifacts_dir = harness_authoritative_artifacts_dir(
        &context.runtime.state_dir,
        &context.runtime.repo_slug,
        &context.runtime.branch_name,
    );
    let entries = match fs::read_dir(&artifacts_dir) {
        Ok(entries) => entries,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(ArtifactGateValidationFailure {
                failure_class: FailureClass::MalformedExecutionState,
                message: format!(
                    "Could not inspect authoritative test-plan artifacts in {}: {error}",
                    artifacts_dir.display()
                ),
            });
        }
    };
    let mut candidate_paths = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|error| ArtifactGateValidationFailure {
            failure_class: FailureClass::MalformedExecutionState,
            message: format!(
                "Could not inspect authoritative test-plan artifacts in {}: {error}",
                artifacts_dir.display()
            ),
        })?;
        let candidate_path = entry.path();
        let Some(file_name) = candidate_path.file_name().and_then(|value| value.to_str()) else {
            continue;
        };
        if !file_name.starts_with("test-plan-") || !file_name.ends_with(".md") {
            continue;
        }
        let metadata = match fs::symlink_metadata(&candidate_path) {
            Ok(metadata) => metadata,
            Err(error) => {
                return Err(ArtifactGateValidationFailure {
                    failure_class: FailureClass::MalformedExecutionState,
                    message: format!(
                        "Could not inspect authoritative test-plan artifact {}: {error}",
                        candidate_path.display()
                    ),
                });
            }
        };
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            return Err(ArtifactGateValidationFailure {
                failure_class: FailureClass::MalformedExecutionState,
                message: format!(
                    "Authoritative test-plan artifact {} must be a regular file.",
                    candidate_path.display()
                ),
            });
        }
        candidate_paths.push(candidate_path);
    }
    candidate_paths.sort();
    let mut first_failure = None;
    for candidate_path in candidate_paths {
        match validate_current_branch_test_plan_candidate_for_finish(
            context,
            &candidate_path,
            current_head,
        ) {
            Ok(()) => return Ok(Some(candidate_path)),
            Err(failure) if first_failure.is_none() => first_failure = Some(failure),
            Err(_) => {}
        }
    }
    match first_failure {
        Some(failure) => Err(failure),
        None => Ok(None),
    }
}

pub(super) fn require_current_release_readiness_ready_for_finish(
    context: &ExecutionContext,
    authoritative_state: &AuthoritativeTransitionState,
    current_branch_closure_id: &str,
    current_branch_reviewed_state_id: &str,
    current_base_branch: &str,
    gate: &mut GateState,
) -> bool {
    let Some(current_release_readiness_record_id) = authoritative_state
        .current_release_readiness_record_id()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_docs_state_missing",
            "Finish readiness requires a current release-readiness milestone for the current branch closure.",
            "Run document-release and return with a fresh release-readiness result.",
        );
        return false;
    };
    let Some(record) =
        authoritative_state.release_readiness_record_by_id(&current_release_readiness_record_id)
    else {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_docs_state_missing",
            "Finish readiness requires a current release-readiness milestone for the current branch closure.",
            "Run document-release and return with a fresh release-readiness result.",
        );
        return false;
    };
    if record.record_status != "current" {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "release_artifact_malformed",
            "The current release-readiness record is not marked current.",
            "Repair the authoritative release-readiness record and retry gate-finish.",
        );
        return false;
    }
    if !summary_hash_matches(&record.summary, &record.summary_hash) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "release_artifact_malformed",
            "The current release-readiness record has an invalid summary hash binding.",
            "Repair the authoritative release-readiness record and retry gate-finish.",
        );
        return false;
    }
    if record.branch_closure_id != current_branch_closure_id {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_docs_state_missing",
            "The current release-readiness milestone is not bound to the still-current branch closure.",
            "Run document-release for the current branch closure and retry gate-finish.",
        );
        return false;
    }
    if record.source_plan_path != context.plan_rel
        || record.source_plan_revision != context.plan_document.plan_revision
    {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_plan_mismatch",
            "The current release-readiness milestone does not match the current approved plan revision.",
            "Run document-release for the current approved plan revision.",
        );
        return false;
    }
    if record.branch_name != context.runtime.branch_name {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_branch_mismatch",
            "The current release-readiness milestone does not match the current branch.",
            "Run document-release for the current approved plan revision.",
        );
        return false;
    }
    if record.base_branch.trim().is_empty() {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_base_branch_unresolved",
            "The current release-readiness milestone is missing its base branch binding.",
            "Run document-release for the current approved plan revision.",
        );
        return false;
    }
    if record.base_branch != current_base_branch {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_base_branch_mismatch",
            "The current release-readiness milestone does not match the expected base branch.",
            "Run document-release for the current approved plan revision.",
        );
        return false;
    }
    if record.repo_slug != context.runtime.repo_slug {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_repo_mismatch",
            "The current release-readiness milestone does not match the current repo.",
            "Run document-release for the current approved plan revision.",
        );
        return false;
    }
    if record.reviewed_state_id != current_branch_reviewed_state_id {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_head_mismatch",
            "The current release-readiness milestone does not match the current reviewed branch state.",
            "Run document-release for the current branch closure and retry gate-finish.",
        );
        return false;
    }
    if record.generated_by_identity != "featureforge/release-readiness" {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_artifact_generator_mismatch",
            "The current release-readiness milestone has an invalid generated-by identity.",
            "Repair the authoritative release-readiness record and retry gate-finish.",
        );
        return false;
    }
    if record.result != "ready" {
        gate.fail(
            FailureClass::ReleaseArtifactNotFresh,
            "release_result_not_pass",
            "The current release-readiness milestone is not ready.",
            "Resolve the release blocker and rerun document-release.",
        );
        return false;
    }
    true
}

pub(super) fn require_current_final_review_pass_for_finish(
    context: &ExecutionContext,
    authoritative_state: &AuthoritativeTransitionState,
    current_branch_closure_id: &str,
    current_branch_reviewed_state_id: &str,
    current_base_branch: &str,
    gate: &mut GateState,
) -> bool {
    let Some(current_release_readiness_record_id) = authoritative_state
        .current_release_readiness_record_id()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_release_binding_missing",
            "The current final-review milestone is missing its release-readiness dependency binding.",
            "Run document-release, then rerun requesting-code-review for the current branch closure.",
        );
        return false;
    };
    let Some(current_final_review_record_id) = authoritative_state
        .current_final_review_record_id()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_missing",
            "Finish readiness requires a current final-review milestone for the current branch closure.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    };
    let Some(record) =
        authoritative_state.final_review_record_by_id(&current_final_review_record_id)
    else {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_missing",
            "Finish readiness requires a current final-review milestone for the current branch closure.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    };
    if record.record_status != "current" {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review record is not marked current.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    if !summary_hash_matches(&record.summary, &record.summary_hash) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review record has an invalid summary hash binding.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    if record.branch_closure_id != current_branch_closure_id {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_missing",
            "The current final-review milestone is not bound to the still-current branch closure.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.release_readiness_record_id.as_deref()
        != Some(current_release_readiness_record_id.as_str())
    {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_release_binding_mismatch",
            "The current final-review milestone is not bound to the current release-readiness milestone identity.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.source_plan_path != context.plan_rel
        || record.source_plan_revision != context.plan_document.plan_revision
    {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_plan_mismatch",
            "The current final-review milestone does not match the current approved plan revision.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.branch_name != context.runtime.branch_name {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_branch_mismatch",
            "The current final-review milestone does not match the current branch.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.base_branch.trim().is_empty() {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_base_branch_unresolved",
            "The current final-review milestone is missing its base branch binding.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.base_branch != current_base_branch {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_base_branch_mismatch",
            "The current final-review milestone does not match the expected base branch.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.repo_slug != context.runtime.repo_slug {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_repo_mismatch",
            "The current final-review milestone does not match the current repo.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if record.reviewed_state_id != current_branch_reviewed_state_id {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_artifact_reviewed_state_mismatch",
            "The current final-review milestone does not match the current reviewed branch state.",
            "Run requesting-code-review and return with a fresh final-review result.",
        );
        return false;
    }
    if !shared_reviewer_source_is_valid(&record.reviewer_source) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_reviewer_source_invalid",
            "The current final-review milestone has an invalid reviewer source.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    if record.dispatch_id.trim().is_empty() || record.reviewer_id.trim().is_empty() {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review milestone is missing dispatch or reviewer identity bindings.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    let expected_browser_qa_required = match context.plan_document.qa_requirement.as_deref() {
        Some("required") => Some(true),
        Some("not-required") => Some(false),
        _ => None,
    };
    if record.browser_qa_required != expected_browser_qa_required {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review milestone has a QA-requirement binding that does not match the approved plan.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    if record.result != "pass" {
        gate.fail(
            FailureClass::ReviewArtifactNotFresh,
            "review_result_not_pass",
            "The current final-review milestone is not pass.",
            "Address the final-review findings and rerun requesting-code-review.",
        );
        return false;
    }
    if !validate_current_final_review_authoritative_bindings(context, &record, gate) {
        return false;
    }
    true
}

fn validate_current_final_review_authoritative_bindings(
    context: &ExecutionContext,
    record: &crate::execution::transitions::CurrentFinalReviewRecord,
    gate: &mut GateState,
) -> bool {
    let Some(final_review_fingerprint) = record
        .final_review_fingerprint
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review milestone is missing its authoritative artifact fingerprint binding.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    };
    if !is_canonical_sha256_fingerprint(final_review_fingerprint) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "The current final-review milestone has a non-canonical authoritative artifact fingerprint binding.",
            "Repair the authoritative final-review record and retry gate-finish.",
        );
        return false;
    }
    let expected_strategy_checkpoint_fingerprint =
        match authoritative_strategy_checkpoint_fingerprint_checked(context) {
            Ok(Some(fingerprint)) if !fingerprint.trim().is_empty() => fingerprint,
            Ok(_) => {
                gate.fail(
                    FailureClass::MalformedExecutionState,
                    "review_artifact_malformed",
                    "Authoritative strategy checkpoint provenance is missing for current final-review validation.",
                    "Restore authoritative strategy checkpoint provenance and retry gate-finish.",
                );
                return false;
            }
            Err(error) => {
                gate.fail(
                    FailureClass::MalformedExecutionState,
                    "review_artifact_malformed",
                    error.message,
                    "Restore authoritative strategy checkpoint provenance and retry gate-finish.",
                );
                return false;
            }
        };
    let expected_strategy_checkpoint_fingerprint =
        expected_strategy_checkpoint_fingerprint.trim().to_owned();
    if !is_canonical_sha256_fingerprint(&expected_strategy_checkpoint_fingerprint) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "review_artifact_malformed",
            "Authoritative strategy checkpoint provenance must be a canonical fingerprint for current final-review validation.",
            "Restore authoritative strategy checkpoint provenance and retry gate-finish.",
        );
        return false;
    };
    true
}

fn is_canonical_sha256_fingerprint(value: &str) -> bool {
    value.len() == 64 && value.chars().all(|ch| ch.is_ascii_hexdigit())
}

pub(super) fn require_current_browser_qa_pass_for_finish(
    context: &ExecutionContext,
    authoritative_state: &AuthoritativeTransitionState,
    current_branch_closure_id: &str,
    current_branch_reviewed_state_id: &str,
    current_base_branch: &str,
    gate: &mut GateState,
) -> bool {
    let Some(current_final_review_record_id) = authoritative_state
        .current_final_review_record_id()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "qa_artifact_malformed",
            "The current QA milestone is missing its final-review dependency binding.",
            "Run requesting-code-review, then rerun qa-only for the current branch closure.",
        );
        return false;
    };
    let Some(current_qa_record_id) = authoritative_state
        .current_qa_record_id()
        .map(|value| value.trim().to_owned())
        .filter(|value| !value.is_empty())
    else {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_missing",
            "Finish readiness requires a current QA milestone for the current branch closure.",
            "Run qa-only and return with a fresh QA result.",
        );
        return false;
    };
    let Some(record) = authoritative_state.browser_qa_record_by_id(&current_qa_record_id) else {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_missing",
            "Finish readiness requires a current QA milestone for the current branch closure.",
            "Run qa-only and return with a fresh QA result.",
        );
        return false;
    };
    if record.record_status != "current" {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "qa_artifact_malformed",
            "The current QA record is not marked current.",
            "Repair the authoritative QA record and retry gate-finish.",
        );
        return false;
    }
    if !summary_hash_matches(&record.summary, &record.summary_hash) {
        gate.fail(
            FailureClass::MalformedExecutionState,
            "qa_artifact_malformed",
            "The current QA record has an invalid summary hash binding.",
            "Repair the authoritative QA record and retry gate-finish.",
        );
        return false;
    }
    if !require_authoritative_test_plan_binding_for_current_qa(context, &record, gate) {
        return false;
    }
    if record.branch_closure_id != current_branch_closure_id {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_missing",
            "The current QA milestone is not bound to the still-current branch closure.",
            "Run qa-only and return with a fresh QA result.",
        );
        return false;
    }
    if record.final_review_record_id.as_deref() != Some(current_final_review_record_id.as_str()) {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_review_binding_mismatch",
            "The current QA milestone is not bound to the current final-review milestone identity.",
            "Run qa-only and return with a fresh QA result.",
        );
        return false;
    }
    if record.source_plan_path != context.plan_rel
        || record.source_plan_revision != context.plan_document.plan_revision
    {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_plan_mismatch",
            "The current QA milestone does not match the current approved plan revision.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.branch_name != context.runtime.branch_name {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_branch_mismatch",
            "The current QA milestone does not match the current branch.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.base_branch.trim().is_empty() {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_base_branch_unresolved",
            "The current QA milestone is missing its base branch binding.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.base_branch != current_base_branch {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_base_branch_mismatch",
            "The current QA milestone does not match the expected base branch.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.repo_slug != context.runtime.repo_slug {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_repo_mismatch",
            "The current QA milestone does not match the current repo.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.reviewed_state_id != current_branch_reviewed_state_id {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_head_mismatch",
            "The current QA milestone does not match the current reviewed branch state.",
            "Run qa-only using the latest test-plan handoff.",
        );
        return false;
    }
    if record.generated_by_identity != "featureforge/qa" {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_artifact_generator_mismatch",
            "The current QA milestone has an invalid generated-by identity.",
            "Repair the authoritative QA record and retry gate-finish.",
        );
        return false;
    }
    if record.result != "pass" {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_result_not_pass",
            "The current QA milestone is not pass.",
            "Address the QA findings and rerun qa-only.",
        );
        return false;
    }
    true
}

fn require_authoritative_test_plan_binding_for_current_qa(
    _context: &ExecutionContext,
    record: &CurrentBrowserQaRecord,
    gate: &mut GateState,
) -> bool {
    let Some(_test_plan_fingerprint) =
        record
            .source_test_plan_fingerprint
            .as_deref()
            .and_then(|value| {
                let value = value.trim();
                (!value.is_empty()).then_some(value)
            })
    else {
        gate.fail(
            FailureClass::QaArtifactNotFresh,
            "qa_source_test_plan_mismatch",
            "The current QA milestone is missing its authoritative test-plan binding.",
            "Refresh the current test plan and rerun QA before gate-finish.",
        );
        return false;
    };
    true
}
