use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde_json::Value;

use crate::diagnostics::{FailureClass, JsonFailure};
use crate::git::sha256_hex;
use crate::paths::harness_state_path;

pub(crate) const GENERATED_BY_WORKFLOW_TRANSFER_RECORD: &str =
    "featureforge:plan-execution-transfer";

#[derive(Clone, Copy)]
pub(crate) struct WorkflowTransferRecordIdentity<'a> {
    pub repo_slug: &'a str,
    pub safe_branch: &'a str,
    pub plan_path: &'a str,
    pub branch_name: &'a str,
    pub head_sha: &'a str,
}

#[derive(Clone, Copy)]
pub(crate) struct WorkflowTransferRecordInput<'a> {
    pub scope: &'a str,
    pub to: &'a str,
    pub reason: &'a str,
}

pub(crate) fn current_workflow_transfer_record_exists(
    state_dir: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
) -> bool {
    let Some(checkpoint) = authoritative_handoff_checkpoint(state_dir, identity) else {
        return false;
    };
    if checkpoint.handoff_required {
        return false;
    }
    if !workflow_transfer_record_matches_decision(&checkpoint.path, identity) {
        return false;
    }
    let Ok(record_source) = fs::read_to_string(&checkpoint.path) else {
        return false;
    };
    sha256_hex(record_source.as_bytes()) == checkpoint.fingerprint
}

pub(crate) fn latest_matching_workflow_transfer_record(
    state_dir: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
) -> Option<PathBuf> {
    let artifact_dir = workflow_transfer_artifact_dir(state_dir, identity.repo_slug);
    let file_name_fragment = format!("-{}-workflow-transfer-", identity.safe_branch);
    let mut candidates = fs::read_dir(&artifact_dir)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.is_file()
                && path
                    .file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(|name| name.contains(&file_name_fragment))
        })
        .collect::<Vec<_>>();
    candidates.sort_by(|left, right| {
        workflow_transfer_record_sort_key(right, identity.safe_branch).cmp(
            &workflow_transfer_record_sort_key(left, identity.safe_branch),
        )
    });

    candidates
        .into_iter()
        .find(|path| workflow_transfer_record_matches_decision(path, identity))
}

pub(crate) fn latest_matching_workflow_transfer_request_record(
    state_dir: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
    input: WorkflowTransferRecordInput<'_>,
) -> Option<PathBuf> {
    let normalized_reason = normalize_reason(input.reason);
    latest_matching_workflow_transfer_record(state_dir, identity).filter(|path| {
        let headers = parse_headers_file(path);
        headers.get("Scope") == Some(&input.scope.to_owned())
            && headers.get("To") == Some(&input.to.to_owned())
            && headers.get("Reason") == Some(&normalized_reason)
    })
}

pub(crate) fn write_workflow_transfer_record(
    state_dir: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
    input: WorkflowTransferRecordInput<'_>,
) -> Result<(PathBuf, String), JsonFailure> {
    let artifact_dir = workflow_transfer_artifact_dir(state_dir, identity.repo_slug);
    fs::create_dir_all(&artifact_dir).map_err(|error| {
        JsonFailure::new(
            FailureClass::PartialAuthoritativeMutation,
            format!(
                "Could not create workflow transfer artifact directory {}: {error}",
                artifact_dir.display()
            ),
        )
    })?;

    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let user_name = current_user_name();
    let normalized_reason = normalize_reason(input.reason);
    let source = format!(
        "# Workflow Transfer Record\n**Source Plan:** `{}`\n**Branch:** {}\n**Repo:** {}\n**Head SHA:** {}\n**Scope:** {}\n**To:** {}\n**Reason:** {}\n**Generated By:** {}\n**Generated At:** {}\n",
        identity.plan_path,
        identity.branch_name,
        identity.repo_slug,
        identity.head_sha,
        input.scope,
        input.to,
        normalized_reason,
        GENERATED_BY_WORKFLOW_TRANSFER_RECORD,
        timestamp,
    );
    let fingerprint = sha256_hex(source.as_bytes());

    loop {
        let path = next_workflow_transfer_record_path(
            &artifact_dir,
            &user_name,
            identity.safe_branch,
            timestamp,
        );
        match fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
        {
            Ok(mut file) => {
                file.write_all(source.as_bytes()).map_err(|error| {
                    JsonFailure::new(
                        FailureClass::PartialAuthoritativeMutation,
                        format!(
                            "Could not write workflow transfer record {}: {error}",
                            path.display()
                        ),
                    )
                })?;
                return Ok((path, fingerprint));
            }
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(JsonFailure::new(
                    FailureClass::PartialAuthoritativeMutation,
                    format!(
                        "Could not write workflow transfer record {}: {error}",
                        path.display()
                    ),
                ));
            }
        }
    }
}

fn workflow_transfer_record_matches_decision(
    path: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
) -> bool {
    let headers = parse_headers_file(path);
    headers.get("Source Plan") == Some(&format!("`{}`", identity.plan_path))
        && headers.get("Branch") == Some(&identity.branch_name.to_owned())
        && headers.get("Repo") == Some(&identity.repo_slug.to_owned())
        && headers.get("Head SHA") == Some(&identity.head_sha.to_owned())
        && headers.get("Generated By") == Some(&String::from(GENERATED_BY_WORKFLOW_TRANSFER_RECORD))
}

struct HandoffCheckpoint {
    path: PathBuf,
    fingerprint: String,
    handoff_required: bool,
}

fn authoritative_handoff_checkpoint(
    state_dir: &Path,
    identity: WorkflowTransferRecordIdentity<'_>,
) -> Option<HandoffCheckpoint> {
    let state_path = harness_state_path(state_dir, identity.repo_slug, identity.branch_name);
    let source = fs::read_to_string(state_path).ok()?;
    let payload: Value = serde_json::from_str(&source).ok()?;
    let root = payload.as_object()?;
    let path = root
        .get("last_handoff_path")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())?;
    let fingerprint = root
        .get("last_handoff_fingerprint")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())?;
    let handoff_required = root
        .get("handoff_required")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    Some(HandoffCheckpoint {
        path: PathBuf::from(path),
        fingerprint: fingerprint.to_owned(),
        handoff_required,
    })
}

fn workflow_transfer_artifact_dir(state_dir: &Path, repo_slug: &str) -> PathBuf {
    state_dir.join("projects").join(repo_slug)
}

fn current_user_name() -> String {
    let raw = env::var("USER")
        .or_else(|_| env::var("USERNAME"))
        .unwrap_or_else(|_| String::from("user"));
    let sanitized = raw
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect::<String>();
    let trimmed = sanitized.trim_matches('-');
    if trimmed.is_empty() {
        String::from("user")
    } else {
        trimmed.to_owned()
    }
}

fn next_workflow_transfer_record_path(
    artifact_dir: &Path,
    user_name: &str,
    safe_branch: &str,
    timestamp: u64,
) -> PathBuf {
    let base_name = format!("{user_name}-{safe_branch}-workflow-transfer-{timestamp}");
    let mut suffix = 0_u32;
    loop {
        let file_name = if suffix == 0 {
            format!("{base_name}.md")
        } else {
            format!("{base_name}-{suffix}.md")
        };
        let candidate = artifact_dir.join(file_name);
        if !candidate.exists() {
            return candidate;
        }
        suffix += 1;
    }
}

fn workflow_transfer_record_sort_key(path: &Path, safe_branch: &str) -> (u64, u32, String) {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default();
    let marker = format!("-{safe_branch}-workflow-transfer-");
    let Some(tail) = file_name
        .strip_suffix(".md")
        .and_then(|name| name.rsplit_once(&marker).map(|(_, tail)| tail))
    else {
        return (0, 0, file_name.to_owned());
    };

    let (timestamp, suffix) = match tail.split_once('-') {
        Some((timestamp, suffix)) => (
            timestamp.parse::<u64>().unwrap_or_default(),
            suffix.parse::<u32>().unwrap_or_default(),
        ),
        None => (tail.parse::<u64>().unwrap_or_default(), 0),
    };
    (timestamp, suffix, file_name.to_owned())
}

fn normalize_reason(reason: &str) -> String {
    reason.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn parse_headers_file(path: &Path) -> BTreeMap<String, String> {
    let source = match fs::read_to_string(path) {
        Ok(source) => source,
        Err(_) => return BTreeMap::new(),
    };
    source
        .lines()
        .filter_map(parse_header_line)
        .collect::<BTreeMap<_, _>>()
}

fn parse_header_line(line: &str) -> Option<(String, String)> {
    let trimmed = line.trim();
    let rest = trimmed.strip_prefix("**")?;
    let (key, value) = rest.split_once(":** ")?;
    Some((key.to_owned(), value.to_owned()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_transfer_record(
        state_dir: &Path,
        repo_slug: &str,
        file_name: &str,
        identity: WorkflowTransferRecordIdentity<'_>,
    ) -> PathBuf {
        let path = state_dir.join("projects").join(repo_slug).join(file_name);
        fs::create_dir_all(path.parent().expect("transfer record should have a parent"))
            .expect("transfer record parent should be creatable");
        fs::write(
            &path,
            format!(
                "# Workflow Transfer Record\n**Source Plan:** `{}`\n**Branch:** {}\n**Repo:** {}\n**Head SHA:** {}\n**Scope:** task\n**To:** teammate\n**Reason:** handoff required\n**Generated By:** {}\n**Generated At:** 1712000000\n",
                identity.plan_path,
                identity.branch_name,
                identity.repo_slug,
                identity.head_sha,
                GENERATED_BY_WORKFLOW_TRANSFER_RECORD,
            ),
        )
        .expect("transfer record should write");
        path
    }

    #[test]
    fn latest_matching_workflow_transfer_record_uses_numeric_collision_suffix_order() {
        let state_dir = TempDir::new().expect("state dir should create");
        let identity = WorkflowTransferRecordIdentity {
            repo_slug: "featureforge-test",
            safe_branch: "feature-branch",
            plan_path: "docs/featureforge/plans/example.md",
            branch_name: "feature/branch",
            head_sha: "abc123",
        };
        write_transfer_record(
            state_dir.path(),
            identity.repo_slug,
            "tester-feature-branch-workflow-transfer-1712000000.md",
            identity,
        );
        write_transfer_record(
            state_dir.path(),
            identity.repo_slug,
            "tester-feature-branch-workflow-transfer-1712000000-2.md",
            identity,
        );
        let latest = write_transfer_record(
            state_dir.path(),
            identity.repo_slug,
            "tester-feature-branch-workflow-transfer-1712000000-10.md",
            identity,
        );

        assert_eq!(
            latest_matching_workflow_transfer_record(state_dir.path(), identity),
            Some(latest)
        );
    }

    #[test]
    fn current_workflow_transfer_record_exists_prefers_authoritative_checkpoint_over_newer_decoy() {
        let state_dir = TempDir::new().expect("state dir should create");
        let identity = WorkflowTransferRecordIdentity {
            repo_slug: "featureforge-test",
            safe_branch: "feature-branch",
            plan_path: "docs/featureforge/plans/example.md",
            branch_name: "feature/branch",
            head_sha: "abc123",
        };
        let authoritative = write_transfer_record(
            state_dir.path(),
            identity.repo_slug,
            "tester-feature-branch-workflow-transfer-1712000000.md",
            identity,
        );
        let _decoy = write_transfer_record(
            state_dir.path(),
            identity.repo_slug,
            "tester-feature-branch-workflow-transfer-1712000001.md",
            identity,
        );
        let authoritative_source =
            fs::read_to_string(&authoritative).expect("authoritative transfer record should read");
        let authoritative_fingerprint = sha256_hex(authoritative_source.as_bytes());
        let harness_state_path =
            harness_state_path(state_dir.path(), identity.repo_slug, identity.branch_name);
        fs::create_dir_all(
            harness_state_path
                .parent()
                .expect("harness state path should have a parent"),
        )
        .expect("branch harness directory should create");
        fs::write(
            &harness_state_path,
            serde_json::json!({
                "last_handoff_path": authoritative,
                "last_handoff_fingerprint": authoritative_fingerprint,
                "handoff_required": false,
            })
            .to_string(),
        )
        .expect("authoritative harness state should write");

        assert!(current_workflow_transfer_record_exists(
            state_dir.path(),
            identity
        ));
    }
}
