use std::fs;
use std::io::ErrorKind;
use std::path::{Component, Path, PathBuf};

use jiff::Timestamp;
use sha2::{Digest, Sha256};

use crate::diagnostics::{FailureClass, JsonFailure};
use crate::execution::final_review::{
    authoritative_strategy_checkpoint_fingerprint_checked, parse_artifact_document,
};
use crate::execution::state::{ExecutionContext, ExecutionRuntime};
use crate::execution::transitions::{
    AuthoritativeTransitionState, CurrentBrowserQaRecord, CurrentFinalReviewRecord,
    CurrentReleaseReadinessRecord,
};
use crate::paths::{atomic_publish_temp_path, harness_authoritative_artifact_path};

pub(crate) struct BranchClosureProjectionInput<'a> {
    pub(crate) contract_identity: &'a str,
    pub(crate) base_branch: &'a str,
    pub(crate) reviewed_state_id: &'a str,
    pub(crate) effective_reviewed_branch_surface: &'a str,
    pub(crate) source_task_closure_ids: &'a [String],
    pub(crate) provenance_basis: &'a str,
    pub(crate) superseded_branch_closure_ids: &'a [String],
}

pub(crate) struct FinalReviewProjectionInput<'a> {
    pub(crate) dispatch_id: &'a str,
    pub(crate) reviewer_source: &'a str,
    pub(crate) reviewer_id: &'a str,
    pub(crate) result: &'a str,
    pub(crate) deviations_required: bool,
    pub(crate) summary: &'a str,
}

pub(crate) struct RenderedFinalReviewArtifacts {
    pub(crate) reviewer_artifact_path: PathBuf,
    pub(crate) reviewer_source_text: String,
    pub(crate) final_review_source: String,
}

pub(crate) struct QaProjectionInput<'a> {
    pub(crate) branch_closure_id: &'a str,
    pub(crate) reviewed_state_id: &'a str,
    pub(crate) result: &'a str,
    pub(crate) summary: &'a str,
    pub(crate) base_branch: &'a str,
    pub(crate) test_plan_path: Option<&'a Path>,
}

pub(crate) fn render_branch_closure_artifact(
    context: &ExecutionContext,
    branch_closure_id: &str,
    projection: BranchClosureProjectionInput<'_>,
) -> Result<String, JsonFailure> {
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let source_task_closure_ids = if projection.source_task_closure_ids.is_empty() {
        String::from("none")
    } else {
        projection.source_task_closure_ids.join(", ")
    };
    let superseded_branch_closure_ids = if projection.superseded_branch_closure_ids.is_empty() {
        String::from("none")
    } else {
        projection.superseded_branch_closure_ids.join(", ")
    };
    Ok(format!(
        "# Branch Closure Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Contract Identity:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed State ID:** {}\n**Effective Reviewed Branch Surface:** {}\n**Source Task Closure IDs:** {}\n**Provenance Basis:** {}\n**Closure Status:** current\n**Superseded Branch Closure IDs:** {}\n**Branch Closure ID:** {}\n**Generated By:** featureforge:record-branch-closure\n**Generated At:** {generated_at}\n\n## Summary\n- current reviewed branch state recorded for late-stage binding.\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        projection.contract_identity,
        context.runtime.branch_name,
        context.runtime.repo_slug,
        projection.base_branch,
        current_head,
        projection.reviewed_state_id,
        projection.effective_reviewed_branch_surface,
        source_task_closure_ids,
        projection.provenance_basis,
        superseded_branch_closure_ids,
        branch_closure_id
    ))
}

pub(crate) fn render_release_readiness_artifact(
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    base_branch: &str,
    result: &str,
    summary: &str,
) -> Result<String, JsonFailure> {
    let base_branch = base_branch.trim();
    if base_branch.is_empty() {
        return Err(JsonFailure::new(
            FailureClass::ReleaseArtifactNotFresh,
            "advance-late-stage release-readiness requires a non-empty bound base branch.",
        ));
    }
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let artifact_result = if result == "ready" { "pass" } else { "blocked" };
    Ok(format!(
        "# Release Readiness Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge:document-release\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        context.runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        artifact_result,
        summary
    ))
}

pub(crate) fn render_final_review_artifacts(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    base_branch: &str,
    inputs: FinalReviewProjectionInput<'_>,
) -> Result<RenderedFinalReviewArtifacts, JsonFailure> {
    render_final_review_artifacts_with_generated_at(
        runtime,
        context,
        branch_closure_id,
        reviewed_state_id,
        base_branch,
        inputs,
        None,
    )
}

fn render_final_review_artifacts_with_generated_at(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    base_branch: &str,
    inputs: FinalReviewProjectionInput<'_>,
    generated_at_override: Option<&str>,
) -> Result<RenderedFinalReviewArtifacts, JsonFailure> {
    let current_head = context.current_head_sha()?;
    let strategy_checkpoint_fingerprint =
        authoritative_strategy_checkpoint_fingerprint_checked(context)?.unwrap_or_default();
    let generated_at = generated_at_override
        .map(str::to_owned)
        .unwrap_or_else(|| Timestamp::now().to_string());
    let recorded_execution_deviations = if inputs.deviations_required {
        "present"
    } else {
        "none"
    };
    let deviation_review_verdict = if inputs.deviations_required {
        "pass"
    } else {
        "not_required"
    };
    let reviewer_artifact_path = project_artifact_dir(runtime).join(format!(
        "featureforge-{}-independent-review-{}.md",
        runtime.safe_branch,
        timestamp_slug()
    ));
    let reviewer_source_text = format!(
        "# Code Review Result\n**Review Stage:** featureforge:requesting-code-review\n**Reviewer Provenance:** dedicated-independent\n**Reviewer Source:** {}\n**Reviewer ID:** {}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Distinct From Stages:** featureforge:executing-plans, featureforge:subagent-driven-development\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge:requesting-code-review\n**Generated At:** {generated_at}\n\n## Summary\n- dedicated independent reviewer artifact fixture.\n- {}\n",
        inputs.reviewer_source,
        inputs.reviewer_id,
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        inputs.result,
        inputs.summary
    );
    let reviewer_artifact_fingerprint = sha256_hex(reviewer_source_text.as_bytes());
    let final_review_source = format!(
        "# Code Review Result\n**Review Stage:** featureforge:requesting-code-review\n**Reviewer Provenance:** dedicated-independent\n**Reviewer Source:** {}\n**Reviewer ID:** {}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Reviewer Artifact Path:** `{}`\n**Reviewer Artifact Fingerprint:** {}\n**Distinct From Stages:** featureforge:executing-plans, featureforge:subagent-driven-development\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Dispatch ID:** {}\n**Result:** {}\n**Generated By:** featureforge:requesting-code-review\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        inputs.reviewer_source,
        inputs.reviewer_id,
        reviewer_artifact_path.display(),
        reviewer_artifact_fingerprint,
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        inputs.dispatch_id,
        inputs.result,
        inputs.summary
    );
    Ok(RenderedFinalReviewArtifacts {
        reviewer_artifact_path,
        reviewer_source_text,
        final_review_source,
    })
}

pub(crate) fn render_qa_artifact(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    inputs: QaProjectionInput<'_>,
) -> Result<String, JsonFailure> {
    let QaProjectionInput {
        branch_closure_id,
        reviewed_state_id,
        result,
        summary,
        base_branch,
        test_plan_path,
    } = inputs;
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let source_test_plan_header = test_plan_path.map_or(String::new(), |path| {
        format!("**Source Test Plan:** `{}`\n", path.display())
    });
    Ok(format!(
        "# QA Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n{}**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge/qa\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        source_test_plan_header,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        result,
        summary
    ))
}

pub(crate) fn regenerate_projection_artifacts_from_authoritative_state(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    authoritative_state: &AuthoritativeTransitionState,
) -> Result<Vec<String>, JsonFailure> {
    let mut regenerated = Vec::new();
    if let Some(identity) = authoritative_state.bound_current_branch_closure_identity()
        && let Some(record) = authoritative_state.branch_closure_record(&identity.branch_closure_id)
    {
        regenerate_branch_closure_projection(
            runtime,
            context,
            &identity.branch_closure_id,
            &identity.reviewed_state_id,
            &record,
        )?;
        regenerated.push(String::from("branch_closure_projection"));
    }
    if let Some(record) = authoritative_state.current_release_readiness_record() {
        regenerate_release_readiness_projection(runtime, context, &record)?;
        regenerated.push(String::from("release_readiness_projection"));
    }
    if let Some(record) = authoritative_state.current_final_review_record() {
        regenerate_final_review_projection(runtime, context, &record)?;
        regenerated.push(String::from("final_review_projection"));
    }
    if let Some(record) = authoritative_state.current_browser_qa_record() {
        regenerate_browser_qa_projection(runtime, context, &record)?;
        regenerated.push(String::from("browser_qa_projection"));
    }
    Ok(regenerated)
}

pub(crate) fn project_artifact_dir(runtime: &ExecutionRuntime) -> PathBuf {
    runtime.state_dir.join("projects").join(&runtime.repo_slug)
}

pub(crate) fn write_project_artifact(
    runtime: &ExecutionRuntime,
    artifact_name: &str,
    source: &str,
) -> Result<(), JsonFailure> {
    let dir = project_artifact_dir(runtime);
    let target = normalize_project_artifact_target(&dir, Path::new(artifact_name))?;
    write_runtime_owned_project_artifact(&dir, &target, source, "Could not write project artifact")
}

pub(crate) fn write_project_artifact_at_path(
    runtime: &ExecutionRuntime,
    artifact_path: &Path,
    source: &str,
) -> Result<(), JsonFailure> {
    let dir = project_artifact_dir(runtime);
    let target = normalize_project_artifact_target(&dir, artifact_path)?;
    write_runtime_owned_project_artifact(&dir, &target, source, "Could not write project artifact")
}

fn write_runtime_owned_project_artifact(
    project_dir: &Path,
    target: &Path,
    source: &str,
    message_prefix: &str,
) -> Result<(), JsonFailure> {
    fs::create_dir_all(project_dir).map_err(|error| {
        JsonFailure::new(
            FailureClass::EvidenceWriteFailed,
            format!(
                "Could not create project artifact directory {}: {error}",
                project_dir.display()
            ),
        )
    })?;
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                format!(
                    "Could not create project artifact directory {}: {error}",
                    parent.display()
                ),
            )
        })?;
    }
    // Re-validate runtime-owned scope after directory creation and immediately before publish.
    enforce_runtime_owned_project_target(project_dir, target)?;
    ensure_existing_project_segments_not_symlink(project_dir, target)?;
    let temp_path = atomic_publish_temp_path(target);
    ensure_existing_project_segments_not_symlink(project_dir, &temp_path)?;
    fs::write(&temp_path, source).map_err(|error| {
        JsonFailure::new(
            FailureClass::EvidenceWriteFailed,
            format!("{message_prefix} {}: {error}", temp_path.display()),
        )
    })?;
    // Validate again to narrow check-then-use windows before final rename.
    if let Err(error) = enforce_runtime_owned_project_target(project_dir, target) {
        let _ = fs::remove_file(&temp_path);
        return Err(error);
    }
    if let Err(error) = ensure_existing_project_segments_not_symlink(project_dir, target) {
        let _ = fs::remove_file(&temp_path);
        return Err(error);
    }
    if let Err(error) = ensure_existing_project_segments_not_symlink(project_dir, &temp_path) {
        let _ = fs::remove_file(&temp_path);
        return Err(error);
    }
    match fs::rename(&temp_path, target) {
        Ok(()) => Ok(()),
        Err(error) => {
            let _ = fs::remove_file(&temp_path);
            Err(JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                format!("{message_prefix} {}: {error}", target.display()),
            ))
        }
    }
}

fn normalize_project_artifact_target(
    project_dir: &Path,
    artifact_path: &Path,
) -> Result<PathBuf, JsonFailure> {
    let joined_target = if artifact_path.is_absolute() {
        artifact_path.to_path_buf()
    } else {
        project_dir.join(artifact_path)
    };
    let mut normalized_target = PathBuf::new();
    for component in joined_target.components() {
        match component {
            Component::Prefix(value) => normalized_target.push(value.as_os_str()),
            Component::RootDir => normalized_target.push(component.as_os_str()),
            Component::CurDir => {}
            Component::Normal(value) => normalized_target.push(value),
            Component::ParentDir => {
                if !normalized_target.pop() {
                    return Err(JsonFailure::new(
                        FailureClass::StaleProvenance,
                        format!(
                            "Projection regeneration refused non-runtime-owned reviewer projection path {}.",
                            joined_target.display()
                        ),
                    ));
                }
            }
        }
    }
    if !normalized_target.starts_with(project_dir) {
        return Err(JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration refused non-runtime-owned reviewer projection path {}.",
                normalized_target.display()
            ),
        ));
    }
    enforce_runtime_owned_project_target(project_dir, &normalized_target)?;
    Ok(normalized_target)
}

fn enforce_runtime_owned_project_target(
    project_dir: &Path,
    normalized_target: &Path,
) -> Result<(), JsonFailure> {
    let canonical_scope_anchor = canonicalize_existing_ancestor(project_dir)?;
    let canonical_target_anchor = canonicalize_existing_ancestor(normalized_target)?;
    if !canonical_target_anchor.starts_with(&canonical_scope_anchor) {
        return Err(JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration refused non-runtime-owned reviewer projection path {}.",
                normalized_target.display()
            ),
        ));
    }
    ensure_existing_project_segments_not_symlink(project_dir, normalized_target)?;
    Ok(())
}

fn canonicalize_existing_ancestor(path: &Path) -> Result<PathBuf, JsonFailure> {
    let mut cursor = path;
    loop {
        match fs::canonicalize(cursor) {
            Ok(canonical) => return Ok(canonical),
            Err(error) if error.kind() == ErrorKind::NotFound => {
                let Some(parent) = cursor.parent() else {
                    return Err(JsonFailure::new(
                        FailureClass::StaleProvenance,
                        format!(
                            "Projection regeneration refused non-runtime-owned reviewer projection path {}.",
                            path.display()
                        ),
                    ));
                };
                cursor = parent;
            }
            Err(error) => {
                return Err(JsonFailure::new(
                    FailureClass::StaleProvenance,
                    format!(
                        "Projection regeneration could not validate runtime-owned reviewer projection path {}: {}",
                        cursor.display(),
                        error
                    ),
                ));
            }
        }
    }
}

fn ensure_existing_project_segments_not_symlink(
    project_dir: &Path,
    normalized_target: &Path,
) -> Result<(), JsonFailure> {
    let relative = normalized_target.strip_prefix(project_dir).map_err(|_| {
        JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration refused non-runtime-owned reviewer projection path {}.",
                normalized_target.display()
            ),
        )
    })?;
    let mut cursor = project_dir.to_path_buf();
    if let Ok(metadata) = fs::symlink_metadata(&cursor)
        && metadata.file_type().is_symlink()
    {
        return Err(JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration refused reviewer projection path {} because runtime-owned project scope contains a symlinked segment.",
                cursor.display()
            ),
        ));
    }
    for component in relative.components() {
        cursor.push(component.as_os_str());
        match fs::symlink_metadata(&cursor) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(JsonFailure::new(
                    FailureClass::StaleProvenance,
                    format!(
                        "Projection regeneration refused reviewer projection path {} because runtime-owned project scope contains a symlinked segment.",
                        cursor.display()
                    ),
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == ErrorKind::NotFound => break,
            Err(error) => {
                return Err(JsonFailure::new(
                    FailureClass::StaleProvenance,
                    format!(
                        "Projection regeneration could not validate runtime-owned reviewer projection path {}: {}",
                        cursor.display(),
                        error
                    ),
                ));
            }
        }
    }
    Ok(())
}

pub(crate) fn publish_authoritative_artifact(
    runtime: &ExecutionRuntime,
    artifact_prefix: &str,
    source: &str,
) -> Result<String, JsonFailure> {
    let fingerprint = sha256_hex(source.as_bytes());
    let path = harness_authoritative_artifact_path(
        &runtime.state_dir,
        &runtime.repo_slug,
        &runtime.branch_name,
        &format!("{artifact_prefix}-{fingerprint}.md"),
    );
    write_atomic(&path, source, "Could not publish authoritative artifact")?;
    Ok(fingerprint)
}

pub(crate) fn timestamp_slug() -> String {
    Timestamp::now()
        .to_string()
        .chars()
        .filter(|ch| ch.is_ascii_digit())
        .collect()
}

fn regenerate_branch_closure_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    record: &crate::execution::transitions::BranchClosureRecord,
) -> Result<(), JsonFailure> {
    let authoritative_source =
        record
            .branch_closure_fingerprint
            .as_deref()
            .and_then(|fingerprint| {
                read_authoritative_projection(
                    runtime,
                    "branch-closure",
                    fingerprint,
                    "branch closure",
                )
                .ok()
            });
    let source = if let Some(source) = authoritative_source {
        source
    } else {
        render_branch_closure_artifact(
            context,
            branch_closure_id,
            BranchClosureProjectionInput {
                contract_identity: &record.contract_identity,
                base_branch: &record.base_branch,
                reviewed_state_id,
                effective_reviewed_branch_surface: &record._effective_reviewed_branch_surface,
                source_task_closure_ids: &record.source_task_closure_ids,
                provenance_basis: &record.provenance_basis,
                superseded_branch_closure_ids: &[],
            },
        )?
    };
    write_project_artifact(
        runtime,
        &format!("branch-closure-{branch_closure_id}.md"),
        &source,
    )
}

fn regenerate_release_readiness_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentReleaseReadinessRecord,
) -> Result<(), JsonFailure> {
    let authoritative_source = record
        .release_docs_fingerprint
        .as_deref()
        .and_then(|fingerprint| {
            read_authoritative_projection(runtime, "release-docs", fingerprint, "release docs").ok()
        });
    let source = if let Some(source) = authoritative_source
        && (source.contains("**Result:** pass") || source.contains("**Result:** blocked"))
    {
        source
    } else {
        render_release_readiness_artifact(
            context,
            &record.branch_closure_id,
            &record.reviewed_state_id,
            &record.base_branch,
            &record.result,
            &record.summary,
        )?
    };
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-release-readiness-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &source,
    )
}

fn regenerate_final_review_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentFinalReviewRecord,
) -> Result<(), JsonFailure> {
    let summary = if record.summary.trim().is_empty() {
        "Final review recorded without summary content."
    } else {
        record.summary.as_str()
    };
    let authoritative_projection = if let Some(fingerprint) =
        record.final_review_fingerprint.as_deref()
    {
        let path = harness_authoritative_artifact_path(
            &runtime.state_dir,
            &runtime.repo_slug,
            &runtime.branch_name,
            &format!("final-review-{fingerprint}.md"),
        );
        match fs::read_to_string(&path) {
            Ok(source) => {
                let observed_fingerprint = sha256_hex(source.as_bytes());
                if observed_fingerprint != fingerprint {
                    return Err(JsonFailure::new(
                        FailureClass::StaleProvenance,
                        format!(
                            "Projection regeneration refused authoritative final review artifact {} because fingerprint {} does not match expected {fingerprint}.",
                            path.display(),
                            observed_fingerprint
                        ),
                    ));
                }
                Some((path, source))
            }
            Err(error) if error.kind() == ErrorKind::NotFound => None,
            Err(error) => {
                return Err(JsonFailure::new(
                    FailureClass::StaleProvenance,
                    format!(
                        "Projection regeneration requires readable authoritative final review artifact {}: {error}",
                        path.display()
                    ),
                ));
            }
        }
    } else {
        None
    };
    let (
        authoritative_document,
        authoritative_generated_at,
        authoritative_reviewer_path,
        authoritative_reviewer_fingerprint,
    ) = if let Some((authoritative_path, _)) = authoritative_projection.as_ref() {
        let document = parse_artifact_document(authoritative_path);
        let generated_at = document.headers.get("Generated At").cloned();
        let reviewer_path = document
            .headers
            .get("Reviewer Artifact Path")
            .map(|value| value.trim().trim_matches('`').to_owned())
            .filter(|value| !value.is_empty())
            .map(PathBuf::from);
        let reviewer_fingerprint = document
            .headers
            .get("Reviewer Artifact Fingerprint")
            .map(|value| value.trim().to_owned())
            .filter(|value| !value.is_empty());
        (
            Some(document),
            generated_at,
            reviewer_path,
            reviewer_fingerprint,
        )
    } else {
        (None, None, None, None)
    };
    let authoritative_reviewer_path = authoritative_reviewer_path
        .as_deref()
        .map(|path| normalize_project_artifact_target(&project_artifact_dir(runtime), path))
        .transpose()?;
    let artifacts = render_final_review_artifacts_with_generated_at(
        runtime,
        context,
        &record.branch_closure_id,
        &record.reviewed_state_id,
        &record.base_branch,
        FinalReviewProjectionInput {
            dispatch_id: &record.dispatch_id,
            reviewer_source: &record.reviewer_source,
            reviewer_id: &record.reviewer_id,
            result: &record.result,
            deviations_required: record.deviations_required.unwrap_or(false),
            summary,
        },
        authoritative_generated_at.as_deref(),
    )?;
    let regenerated_reviewer_source = if let Some(expected_reviewer_fingerprint) =
        authoritative_reviewer_fingerprint.as_deref()
    {
        let persisted_reviewer_source = authoritative_reviewer_path.as_ref().and_then(|path| {
            fs::read_to_string(path)
                .ok()
                .filter(|source| sha256_hex(source.as_bytes()) == expected_reviewer_fingerprint)
        });
        let synthesized_reviewer_source = persisted_reviewer_source.or_else(|| {
            authoritative_document.as_ref().and_then(|document| {
                reviewer_artifact_candidates_from_authoritative_final_review(
                    document,
                    summary,
                    authoritative_reviewer_path.as_deref(),
                )
                .into_iter()
                .find(|source| sha256_hex(source.as_bytes()) == expected_reviewer_fingerprint)
            })
        });
        let Some(source) = synthesized_reviewer_source else {
            return Err(JsonFailure::new(
                FailureClass::StaleProvenance,
                "Projection regeneration could not restore reviewer projection content that matches authoritative final-review bindings.",
            ));
        };
        source
    } else {
        artifacts.reviewer_source_text.clone()
    };
    let reviewer_name = artifacts
        .reviewer_artifact_path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| {
            JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                "Could not derive regenerated reviewer artifact file name.",
            )
        })?;
    write_project_artifact(runtime, reviewer_name, &regenerated_reviewer_source)?;
    if let Some(reviewer_path) = authoritative_reviewer_path.as_deref() {
        let canonical_projection_path = project_artifact_dir(runtime).join(reviewer_name);
        if reviewer_path != canonical_projection_path {
            write_project_artifact_at_path(runtime, reviewer_path, &regenerated_reviewer_source)?;
        }
    }
    let final_review_source = authoritative_projection
        .as_ref()
        .map(|(_, source)| source.clone())
        .unwrap_or(artifacts.final_review_source);
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-code-review-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &final_review_source,
    )
}

fn reviewer_artifact_candidates_from_authoritative_final_review(
    final_review_document: &crate::execution::final_review::ArtifactDocument,
    summary: &str,
    reviewer_artifact_path: Option<&Path>,
) -> Vec<String> {
    let header = |key: &str| {
        final_review_document
            .headers
            .get(key)
            .map(String::as_str)
            .map(str::trim)
            .filter(|value| !value.is_empty())
    };
    let Some(review_stage) = header("Review Stage") else {
        return Vec::new();
    };
    let Some(reviewer_provenance) = header("Reviewer Provenance") else {
        return Vec::new();
    };
    let Some(reviewer_source) = header("Reviewer Source") else {
        return Vec::new();
    };
    let Some(reviewer_id) = header("Reviewer ID") else {
        return Vec::new();
    };
    let Some(strategy_checkpoint_fingerprint) = header("Strategy Checkpoint Fingerprint") else {
        return Vec::new();
    };
    let Some(distinct_from_stages) = header("Distinct From Stages") else {
        return Vec::new();
    };
    let Some(recorded_execution_deviations) = header("Recorded Execution Deviations") else {
        return Vec::new();
    };
    let Some(deviation_review_verdict) = header("Deviation Review Verdict") else {
        return Vec::new();
    };
    let Some(source_plan) = header("Source Plan") else {
        return Vec::new();
    };
    let source_plan = source_plan.trim_matches('`');
    let Some(source_plan_revision) = header("Source Plan Revision") else {
        return Vec::new();
    };
    let Some(branch) = header("Branch") else {
        return Vec::new();
    };
    let Some(repo) = header("Repo") else {
        return Vec::new();
    };
    let Some(base_branch) = header("Base Branch") else {
        return Vec::new();
    };
    let Some(head_sha) = header("Head SHA") else {
        return Vec::new();
    };
    let Some(result) = header("Result") else {
        return Vec::new();
    };
    let Some(generated_by) = header("Generated By") else {
        return Vec::new();
    };
    let Some(final_review_generated_at) = header("Generated At") else {
        return Vec::new();
    };

    let reviewer_generated_at = reviewer_artifact_path
        .and_then(generated_at_from_reviewer_artifact_path)
        .filter(|value| value != final_review_generated_at);
    let mut generated_at_candidates = vec![final_review_generated_at.to_owned()];
    if let Some(value) = reviewer_generated_at {
        generated_at_candidates.push(value);
    }
    let mut candidates = Vec::new();
    for generated_at in generated_at_candidates {
        candidates.push(format!(
            "# Code Review Result\n**Review Stage:** {review_stage}\n**Reviewer Provenance:** {reviewer_provenance}\n**Reviewer Source:** {reviewer_source}\n**Reviewer ID:** {reviewer_id}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Distinct From Stages:** {distinct_from_stages}\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Source Plan:** `{source_plan}`\n**Source Plan Revision:** {source_plan_revision}\n**Branch:** {branch}\n**Repo:** {repo}\n**Base Branch:** {base_branch}\n**Head SHA:** {head_sha}\n**Result:** {result}\n**Generated By:** {generated_by}\n**Generated At:** {generated_at}\n\n## Summary\n- dedicated independent reviewer artifact fixture.\n",
        ));
        if let (Some(reviewed_state_id), Some(branch_closure_id)) = (
            header("Current Reviewed Branch State ID"),
            header("Branch Closure ID"),
        ) {
            candidates.push(format!(
                "# Code Review Result\n**Review Stage:** {review_stage}\n**Reviewer Provenance:** {reviewer_provenance}\n**Reviewer Source:** {reviewer_source}\n**Reviewer ID:** {reviewer_id}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Distinct From Stages:** {distinct_from_stages}\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Source Plan:** `{source_plan}`\n**Source Plan Revision:** {source_plan_revision}\n**Branch:** {branch}\n**Repo:** {repo}\n**Base Branch:** {base_branch}\n**Head SHA:** {head_sha}\n**Current Reviewed Branch State ID:** {reviewed_state_id}\n**Branch Closure ID:** {branch_closure_id}\n**Result:** {result}\n**Generated By:** {generated_by}\n**Generated At:** {generated_at}\n\n## Summary\n- dedicated independent reviewer artifact fixture.\n- {summary}\n",
            ));
        }
    }
    candidates
}

fn generated_at_from_reviewer_artifact_path(path: &Path) -> Option<String> {
    let name = path.file_name()?.to_str()?;
    let stem = name.strip_suffix(".md")?;
    let mut pieces = stem.rsplitn(3, '-');
    let stamp = pieces.next()?;
    let date_part = pieces.next()?;
    if stamp.len() != 6
        || date_part.len() != 8
        || !stamp.chars().all(|ch| ch.is_ascii_digit())
        || !date_part.chars().all(|ch| ch.is_ascii_digit())
    {
        return None;
    }
    Some(format!(
        "{}-{}-{}T{}:{}:{}Z",
        &date_part[0..4],
        &date_part[4..6],
        &date_part[6..8],
        &stamp[0..2],
        &stamp[2..4],
        &stamp[4..6],
    ))
}

fn regenerate_browser_qa_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentBrowserQaRecord,
) -> Result<(), JsonFailure> {
    let summary = if record.summary.trim().is_empty() {
        "Browser QA recorded without summary content."
    } else {
        record.summary.as_str()
    };
    let regenerated_test_plan_path = regenerate_test_plan_projection(runtime, record)?;
    let authoritative_source = record
        .browser_qa_fingerprint
        .as_deref()
        .and_then(|fingerprint| {
            read_authoritative_projection(runtime, "browser-qa", fingerprint, "browser QA").ok()
        });
    let source = if let Some(source) = authoritative_source {
        source
    } else {
        render_qa_artifact(
            runtime,
            context,
            QaProjectionInput {
                branch_closure_id: &record.branch_closure_id,
                reviewed_state_id: &record.reviewed_state_id,
                result: &record.result,
                summary,
                base_branch: &record.base_branch,
                test_plan_path: regenerated_test_plan_path.as_deref(),
            },
        )?
    };
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-test-outcome-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &source,
    )
}

fn regenerate_test_plan_projection(
    runtime: &ExecutionRuntime,
    record: &CurrentBrowserQaRecord,
) -> Result<Option<PathBuf>, JsonFailure> {
    let Some(test_plan_fingerprint) = record.source_test_plan_fingerprint.as_deref() else {
        return Ok(None);
    };
    let test_plan_source =
        read_authoritative_projection(runtime, "test-plan", test_plan_fingerprint, "test plan")?;
    let test_plan_name = format!(
        "featureforge-{}-test-plan-{}.md",
        runtime.safe_branch,
        timestamp_slug()
    );
    write_project_artifact(runtime, &test_plan_name, &test_plan_source)?;
    Ok(Some(project_artifact_dir(runtime).join(test_plan_name)))
}

fn read_authoritative_projection(
    runtime: &ExecutionRuntime,
    artifact_prefix: &str,
    fingerprint: &str,
    artifact_label: &str,
) -> Result<String, JsonFailure> {
    let path = harness_authoritative_artifact_path(
        &runtime.state_dir,
        &runtime.repo_slug,
        &runtime.branch_name,
        &format!("{artifact_prefix}-{fingerprint}.md"),
    );
    let source = fs::read_to_string(&path).map_err(|error| {
        JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration requires readable authoritative {artifact_label} artifact {}: {error}",
                path.display()
            ),
        )
    })?;
    let observed_fingerprint = sha256_hex(source.as_bytes());
    if observed_fingerprint != fingerprint {
        return Err(JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration refused authoritative {artifact_label} artifact {} because fingerprint {} does not match expected {fingerprint}.",
                path.display(),
                observed_fingerprint
            ),
        ));
    }
    Ok(source)
}

fn write_atomic(path: &Path, contents: &str, message_prefix: &str) -> Result<(), JsonFailure> {
    write_atomic_inner(path, contents, message_prefix, true)
}

fn write_atomic_inner(
    path: &Path,
    contents: &str,
    message_prefix: &str,
    create_parent: bool,
) -> Result<(), JsonFailure> {
    if create_parent && let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                format!("{message_prefix} {}: {error}", parent.display()),
            )
        })?;
    }
    let temp_path = atomic_publish_temp_path(path);
    fs::write(&temp_path, contents).map_err(|error| {
        JsonFailure::new(
            FailureClass::EvidenceWriteFailed,
            format!("{message_prefix} {}: {error}", temp_path.display()),
        )
    })?;
    match fs::rename(&temp_path, path) {
        Ok(()) => Ok(()),
        Err(error) => {
            let _ = fs::remove_file(&temp_path);
            Err(JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                format!("{message_prefix} {}: {error}", path.display()),
            ))
        }
    }
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("{digest:x}")
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(unix)]
    use std::os::unix::fs::symlink;
    use tempfile::TempDir;

    fn test_runtime(root: &Path) -> ExecutionRuntime {
        ExecutionRuntime {
            repo_root: root.to_path_buf(),
            git_dir: root.join(".git"),
            branch_name: String::from("feature/runtime"),
            repo_slug: String::from("featureforge"),
            safe_branch: String::from("feature-runtime"),
            state_dir: root.join("state"),
        }
    }

    #[test]
    fn project_artifact_write_normalizes_parent_segments_within_runtime_scope() {
        let temp = TempDir::new().expect("temp runtime root should exist");
        let runtime = test_runtime(temp.path());
        write_project_artifact_at_path(
            &runtime,
            Path::new("nested/../reviewer.md"),
            "normalized reviewer projection",
        )
        .expect("writer should accept runtime-owned path with lexical parent segments");
        let expected_path = project_artifact_dir(&runtime).join("reviewer.md");
        assert_eq!(
            fs::read_to_string(&expected_path)
                .expect("normalized reviewer projection should exist"),
            "normalized reviewer projection"
        );
    }

    #[test]
    fn project_artifact_write_rejects_paths_that_escape_runtime_scope() {
        let temp = TempDir::new().expect("temp runtime root should exist");
        let runtime = test_runtime(temp.path());
        let error =
            write_project_artifact_at_path(&runtime, Path::new("../../escape.md"), "escape")
                .expect_err("writer should reject reviewer projection path escapes");
        assert_eq!(error.error_class, FailureClass::StaleProvenance.as_str());
    }

    #[cfg(unix)]
    #[test]
    fn project_artifact_write_rejects_symlinked_path_segments() {
        let temp = TempDir::new().expect("temp runtime root should exist");
        let runtime = test_runtime(temp.path());
        let project_dir = project_artifact_dir(&runtime);
        fs::create_dir_all(&project_dir).expect("project artifact dir should be creatable");
        let outside_dir = temp.path().join("outside");
        fs::create_dir_all(&outside_dir).expect("outside dir should be creatable");
        symlink(&outside_dir, project_dir.join("escaped"))
            .expect("symlinked project segment fixture should be creatable");

        let error = write_project_artifact_at_path(
            &runtime,
            Path::new("escaped/reviewer.md"),
            "escaped projection",
        )
        .expect_err("writer should reject symlinked project path segments");
        assert_eq!(error.error_class, FailureClass::StaleProvenance.as_str());
    }

    #[test]
    fn authoritative_projection_read_rejects_fingerprint_content_mismatch() {
        let temp = TempDir::new().expect("temp runtime root should exist");
        let runtime = test_runtime(temp.path());
        let expected_fingerprint = sha256_hex(b"expected-authoritative-final-review");
        let authoritative_path = harness_authoritative_artifact_path(
            &runtime.state_dir,
            &runtime.repo_slug,
            &runtime.branch_name,
            &format!("final-review-{expected_fingerprint}.md"),
        );
        fs::create_dir_all(
            authoritative_path
                .parent()
                .expect("authoritative projection path should include parent"),
        )
        .expect("authoritative projection parent should be creatable");
        fs::write(
            &authoritative_path,
            "tampered authoritative projection content",
        )
        .expect("tampered authoritative projection should write");

        let error = read_authoritative_projection(
            &runtime,
            "final-review",
            &expected_fingerprint,
            "final review",
        )
        .expect_err("fingerprint/content mismatch should fail closed");
        assert_eq!(error.error_class, FailureClass::StaleProvenance.as_str());
    }
}
