use std::fs;
use std::path::{Path, PathBuf};

use jiff::Timestamp;
use sha2::{Digest, Sha256};

use crate::diagnostics::{FailureClass, JsonFailure};
use crate::execution::final_review::{
    authoritative_strategy_checkpoint_fingerprint_checked,
};
use crate::execution::state::{ExecutionContext, ExecutionRuntime};
use crate::execution::transitions::{
    AuthoritativeTransitionState, CurrentBrowserQaRecord, CurrentFinalReviewRecord,
    CurrentReleaseReadinessRecord,
};
use crate::paths::{harness_authoritative_artifact_path, write_atomic as write_atomic_file};

pub(crate) struct BranchClosureProjectionInput<'a> {
    pub(crate) contract_identity: &'a str,
    pub(crate) base_branch: &'a str,
    pub(crate) reviewed_state_id: &'a str,
    pub(crate) effective_reviewed_branch_surface: &'a str,
    pub(crate) source_task_closure_ids: &'a [String],
    pub(crate) provenance_basis: &'a str,
    pub(crate) superseded_branch_closure_ids: &'a [String],
}

pub(crate) struct FinalReviewProjectionInput<'a> {
    pub(crate) dispatch_id: &'a str,
    pub(crate) reviewer_source: &'a str,
    pub(crate) reviewer_id: &'a str,
    pub(crate) result: &'a str,
    pub(crate) deviations_required: bool,
    pub(crate) summary: &'a str,
}

pub(crate) struct RenderedFinalReviewArtifacts {
    pub(crate) reviewer_artifact_path: PathBuf,
    pub(crate) reviewer_source_text: String,
    pub(crate) final_review_source: String,
}

pub(crate) struct QaProjectionInput<'a> {
    pub(crate) branch_closure_id: &'a str,
    pub(crate) reviewed_state_id: &'a str,
    pub(crate) result: &'a str,
    pub(crate) summary: &'a str,
    pub(crate) base_branch: &'a str,
    pub(crate) test_plan_path: Option<&'a Path>,
}

pub(crate) fn render_branch_closure_artifact(
    context: &ExecutionContext,
    branch_closure_id: &str,
    projection: BranchClosureProjectionInput<'_>,
) -> Result<String, JsonFailure> {
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let source_task_closure_ids = if projection.source_task_closure_ids.is_empty() {
        String::from("none")
    } else {
        projection.source_task_closure_ids.join(", ")
    };
    let superseded_branch_closure_ids = if projection.superseded_branch_closure_ids.is_empty() {
        String::from("none")
    } else {
        projection.superseded_branch_closure_ids.join(", ")
    };
    Ok(format!(
        "# Branch Closure Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Contract Identity:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed State ID:** {}\n**Effective Reviewed Branch Surface:** {}\n**Source Task Closure IDs:** {}\n**Provenance Basis:** {}\n**Closure Status:** current\n**Superseded Branch Closure IDs:** {}\n**Branch Closure ID:** {}\n**Generated By:** featureforge:record-branch-closure\n**Generated At:** {generated_at}\n\n## Summary\n- current reviewed branch state recorded for late-stage binding.\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        projection.contract_identity,
        context.runtime.branch_name,
        context.runtime.repo_slug,
        projection.base_branch,
        current_head,
        projection.reviewed_state_id,
        projection.effective_reviewed_branch_surface,
        source_task_closure_ids,
        projection.provenance_basis,
        superseded_branch_closure_ids,
        branch_closure_id
    ))
}

pub(crate) fn render_release_readiness_artifact(
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    result: &str,
    summary: &str,
) -> Result<String, JsonFailure> {
    let base_branch = context.current_release_base_branch().ok_or_else(|| {
        JsonFailure::new(
            FailureClass::ReleaseArtifactNotFresh,
            "advance-late-stage release-readiness requires a resolvable base branch.",
        )
    })?;
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let artifact_result = if result == "ready" { "pass" } else { "blocked" };
    Ok(format!(
        "# Release Readiness Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge:document-release\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        context.runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        artifact_result,
        summary
    ))
}

pub(crate) fn render_final_review_artifacts(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    base_branch: &str,
    inputs: FinalReviewProjectionInput<'_>,
) -> Result<RenderedFinalReviewArtifacts, JsonFailure> {
    let current_head = context.current_head_sha()?;
    let strategy_checkpoint_fingerprint =
        authoritative_strategy_checkpoint_fingerprint_checked(context)?.unwrap_or_default();
    let generated_at = Timestamp::now().to_string();
    let recorded_execution_deviations = if inputs.deviations_required {
        "present"
    } else {
        "none"
    };
    let deviation_review_verdict = if inputs.deviations_required {
        if inputs.result == "pass" {
            "pass"
        } else {
            "fail"
        }
    } else {
        "not_required"
    };
    let reviewer_artifact_path = project_artifact_dir(runtime).join(format!(
        "featureforge-{}-independent-review-{}.md",
        runtime.safe_branch,
        timestamp_slug()
    ));
    let reviewer_source_text = format!(
        "# Code Review Result\n**Review Stage:** featureforge:requesting-code-review\n**Reviewer Provenance:** dedicated-independent\n**Reviewer Source:** {}\n**Reviewer ID:** {}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Distinct From Stages:** featureforge:executing-plans, featureforge:subagent-driven-development\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge:requesting-code-review\n**Generated At:** {generated_at}\n\n## Summary\n- dedicated independent reviewer artifact fixture.\n- {}\n",
        inputs.reviewer_source,
        inputs.reviewer_id,
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        inputs.result,
        inputs.summary
    );
    let reviewer_artifact_fingerprint = sha256_hex(reviewer_source_text.as_bytes());
    let final_review_source = format!(
        "# Code Review Result\n**Review Stage:** featureforge:requesting-code-review\n**Reviewer Provenance:** dedicated-independent\n**Reviewer Source:** {}\n**Reviewer ID:** {}\n**Strategy Checkpoint Fingerprint:** {strategy_checkpoint_fingerprint}\n**Reviewer Artifact Path:** `{}`\n**Reviewer Artifact Fingerprint:** {}\n**Distinct From Stages:** featureforge:executing-plans, featureforge:subagent-driven-development\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Recorded Execution Deviations:** {recorded_execution_deviations}\n**Deviation Review Verdict:** {deviation_review_verdict}\n**Dispatch ID:** {}\n**Result:** {}\n**Generated By:** featureforge:requesting-code-review\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        inputs.reviewer_source,
        inputs.reviewer_id,
        reviewer_artifact_path.display(),
        reviewer_artifact_fingerprint,
        context.plan_rel,
        context.plan_document.plan_revision,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        inputs.dispatch_id,
        inputs.result,
        inputs.summary
    );
    Ok(RenderedFinalReviewArtifacts {
        reviewer_artifact_path,
        reviewer_source_text,
        final_review_source,
    })
}

pub(crate) fn render_qa_artifact(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    inputs: QaProjectionInput<'_>,
) -> Result<String, JsonFailure> {
    let QaProjectionInput {
        branch_closure_id,
        reviewed_state_id,
        result,
        summary,
        base_branch,
        test_plan_path,
    } = inputs;
    let current_head = context.current_head_sha()?;
    let generated_at = Timestamp::now().to_string();
    let source_test_plan_header = test_plan_path.map_or(String::new(), |path| {
        format!("**Source Test Plan:** `{}`\n", path.display())
    });
    Ok(format!(
        "# QA Result\n**Source Plan:** `{}`\n**Source Plan Revision:** {}\n{}**Branch:** {}\n**Repo:** {}\n**Base Branch:** {}\n**Head SHA:** {}\n**Current Reviewed Branch State ID:** {}\n**Branch Closure ID:** {}\n**Result:** {}\n**Generated By:** featureforge/qa\n**Generated At:** {generated_at}\n\n## Summary\n- {}\n",
        context.plan_rel,
        context.plan_document.plan_revision,
        source_test_plan_header,
        context.runtime.branch_name,
        runtime.repo_slug,
        base_branch,
        current_head,
        reviewed_state_id,
        branch_closure_id,
        result,
        summary
    ))
}

pub(crate) fn regenerate_projection_artifacts_from_authoritative_state(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    authoritative_state: &AuthoritativeTransitionState,
) -> Result<Vec<String>, JsonFailure> {
    let mut regenerated = Vec::new();
    if let Some(identity) = authoritative_state.recoverable_current_branch_closure_identity()
        && let Some(record) = authoritative_state.branch_closure_record(&identity.branch_closure_id)
    {
        regenerate_branch_closure_projection(
            runtime,
            context,
            &identity.branch_closure_id,
            &identity.reviewed_state_id,
            &record,
        )?;
        regenerated.push(String::from("branch_closure_projection"));
    }
    if let Some(record) = authoritative_state.current_release_readiness_record() {
        regenerate_release_readiness_projection(runtime, context, &record)?;
        regenerated.push(String::from("release_readiness_projection"));
    }
    if let Some(record) = authoritative_state.current_final_review_record() {
        regenerate_final_review_projection(runtime, context, &record)?;
        regenerated.push(String::from("final_review_projection"));
    }
    if let Some(record) = authoritative_state.current_browser_qa_record() {
        regenerate_browser_qa_projection(runtime, context, &record)?;
        regenerated.push(String::from("browser_qa_projection"));
    }
    Ok(regenerated)
}

pub(crate) fn project_artifact_dir(runtime: &ExecutionRuntime) -> PathBuf {
    runtime.state_dir.join("projects").join(&runtime.repo_slug)
}

pub(crate) fn write_project_artifact(
    runtime: &ExecutionRuntime,
    artifact_name: &str,
    source: &str,
) -> Result<(), JsonFailure> {
    let dir = project_artifact_dir(runtime);
    fs::create_dir_all(&dir).map_err(|error| {
        JsonFailure::new(
            FailureClass::EvidenceWriteFailed,
            format!(
                "Could not create project artifact directory {}: {error}",
                dir.display()
            ),
        )
    })?;
    write_atomic(
        &dir.join(artifact_name),
        source,
        "Could not write project artifact",
    )
}

pub(crate) fn publish_authoritative_artifact(
    runtime: &ExecutionRuntime,
    artifact_prefix: &str,
    source: &str,
) -> Result<String, JsonFailure> {
    let fingerprint = sha256_hex(source.as_bytes());
    let path = harness_authoritative_artifact_path(
        &runtime.state_dir,
        &runtime.repo_slug,
        &runtime.branch_name,
        &format!("{artifact_prefix}-{fingerprint}.md"),
    );
    write_atomic(&path, source, "Could not publish authoritative artifact")?;
    Ok(fingerprint)
}

pub(crate) fn timestamp_slug() -> String {
    Timestamp::now()
        .to_string()
        .chars()
        .filter(|ch| ch.is_ascii_digit())
        .collect()
}

fn regenerate_branch_closure_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    branch_closure_id: &str,
    reviewed_state_id: &str,
    record: &crate::execution::transitions::BranchClosureRecord,
) -> Result<(), JsonFailure> {
    let authoritative_source = record
        .branch_closure_fingerprint
        .as_deref()
        .and_then(|fingerprint| {
            read_authoritative_projection(runtime, "branch-closure", fingerprint, "branch closure")
                .ok()
        });
    let source = if let Some(source) = authoritative_source {
        source
    } else {
        render_branch_closure_artifact(
            context,
            branch_closure_id,
            BranchClosureProjectionInput {
                contract_identity: &record.contract_identity,
                base_branch: &record.base_branch,
                reviewed_state_id,
                effective_reviewed_branch_surface: &record._effective_reviewed_branch_surface,
                source_task_closure_ids: &record.source_task_closure_ids,
                provenance_basis: &record.provenance_basis,
                superseded_branch_closure_ids: &[],
            },
        )?
    };
    write_project_artifact(
        runtime,
        &format!("branch-closure-{branch_closure_id}.md"),
        &source,
    )
}

fn regenerate_release_readiness_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentReleaseReadinessRecord,
) -> Result<(), JsonFailure> {
    let authoritative_source = record
        .release_docs_fingerprint
        .as_deref()
        .and_then(|fingerprint| {
            read_authoritative_projection(runtime, "release-docs", fingerprint, "release docs").ok()
        });
    let source = if let Some(source) = authoritative_source
        && (source.contains("**Result:** pass") || source.contains("**Result:** blocked"))
    {
        source
    } else {
        render_release_readiness_artifact(
            context,
            &record.branch_closure_id,
            &record.reviewed_state_id,
            &record.result,
            &record.summary,
        )?
    };
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-release-readiness-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &source,
    )
}

fn regenerate_final_review_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentFinalReviewRecord,
) -> Result<(), JsonFailure> {
    let summary = if record.summary.trim().is_empty() {
        "Final review recorded without summary content."
    } else {
        record.summary.as_str()
    };
    let artifacts = render_final_review_artifacts(
        runtime,
        context,
        &record.branch_closure_id,
        &record.reviewed_state_id,
        &record.base_branch,
        FinalReviewProjectionInput {
            dispatch_id: &record.dispatch_id,
            reviewer_source: &record.reviewer_source,
            reviewer_id: &record.reviewer_id,
            result: &record.result,
            deviations_required: record.deviations_required.unwrap_or(false),
            summary,
        },
    )?;
    let reviewer_name = artifacts
        .reviewer_artifact_path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| {
            JsonFailure::new(
                FailureClass::EvidenceWriteFailed,
                "Could not derive regenerated reviewer artifact file name.",
            )
        })?;
    write_project_artifact(runtime, reviewer_name, &artifacts.reviewer_source_text)?;
    let final_review_source = artifacts.final_review_source;
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-code-review-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &final_review_source,
    )
}

fn regenerate_browser_qa_projection(
    runtime: &ExecutionRuntime,
    context: &ExecutionContext,
    record: &CurrentBrowserQaRecord,
) -> Result<(), JsonFailure> {
    let summary = if record.summary.trim().is_empty() {
        "Browser QA recorded without summary content."
    } else {
        record.summary.as_str()
    };
    let regenerated_test_plan_path = regenerate_test_plan_projection(runtime, record)?;
    let authoritative_source = record
        .browser_qa_fingerprint
        .as_deref()
        .and_then(|fingerprint| {
            read_authoritative_projection(runtime, "browser-qa", fingerprint, "browser QA").ok()
        });
    let source = if let Some(source) = authoritative_source {
        source
    } else {
        render_qa_artifact(
            runtime,
            context,
            QaProjectionInput {
                branch_closure_id: &record.branch_closure_id,
                reviewed_state_id: &record.reviewed_state_id,
                result: &record.result,
                summary,
                base_branch: &record.base_branch,
                test_plan_path: regenerated_test_plan_path.as_deref(),
            },
        )?
    };
    write_project_artifact(
        runtime,
        &format!(
            "featureforge-{}-test-outcome-{}.md",
            runtime.safe_branch,
            timestamp_slug()
        ),
        &source,
    )
}

fn regenerate_test_plan_projection(
    runtime: &ExecutionRuntime,
    record: &CurrentBrowserQaRecord,
) -> Result<Option<PathBuf>, JsonFailure> {
    let Some(test_plan_fingerprint) = record.source_test_plan_fingerprint.as_deref() else {
        return Ok(None);
    };
    let test_plan_source =
        read_authoritative_projection(runtime, "test-plan", test_plan_fingerprint, "test plan")?;
    let test_plan_name = format!(
        "featureforge-{}-test-plan-{}.md",
        runtime.safe_branch,
        timestamp_slug()
    );
    write_project_artifact(runtime, &test_plan_name, &test_plan_source)?;
    Ok(Some(project_artifact_dir(runtime).join(test_plan_name)))
}

fn read_authoritative_projection(
    runtime: &ExecutionRuntime,
    artifact_prefix: &str,
    fingerprint: &str,
    artifact_label: &str,
) -> Result<String, JsonFailure> {
    let path = harness_authoritative_artifact_path(
        &runtime.state_dir,
        &runtime.repo_slug,
        &runtime.branch_name,
        &format!("{artifact_prefix}-{fingerprint}.md"),
    );
    fs::read_to_string(&path).map_err(|error| {
        JsonFailure::new(
            FailureClass::StaleProvenance,
            format!(
                "Projection regeneration requires readable authoritative {artifact_label} artifact {}: {error}",
                path.display()
            ),
        )
    })
}

fn write_atomic(path: &Path, contents: &str, message_prefix: &str) -> Result<(), JsonFailure> {
    write_atomic_file(path, contents).map_err(|error| {
        JsonFailure::new(
            FailureClass::EvidenceWriteFailed,
            format!("{message_prefix} {}: {error}", path.display()),
        )
    })
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    format!("{digest:x}")
}
