use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use schemars::JsonSchema;
use serde::Serialize;

use crate::cli::workflow::{OperatorArgs, RecordPivotArgs};
use crate::diagnostics::{DiagnosticError, FailureClass};
use crate::execution::state::{
    ExecutionRuntime, current_head_sha, load_execution_context, status_from_context,
};
use crate::git::discover_slug_identity;
use crate::paths::featureforge_state_dir;
use crate::workflow::operator::operator;

const GENERATED_BY: &str = "featureforge:workflow-record-pivot";

#[derive(Clone, Copy)]
pub(crate) struct WorkflowPivotRecordIdentity<'a> {
    pub repo_slug: &'a str,
    pub safe_branch: &'a str,
    pub plan_path: &'a str,
    pub branch_name: &'a str,
    pub head_sha: &'a str,
    pub decision_reason_codes: &'a [String],
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, JsonSchema)]
pub struct WorkflowPivotRecordOutput {
    pub action: String,
    pub plan_path: String,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub record_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

pub(crate) fn current_workflow_pivot_record_exists(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> bool {
    latest_matching_workflow_pivot_record(state_dir, identity).is_some()
}

pub(crate) fn latest_matching_workflow_pivot_record(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> Option<PathBuf> {
    let artifact_dir = workflow_pivot_artifact_dir(state_dir, identity.repo_slug);
    let decision_reason_codes = render_decision_reason_codes(identity.decision_reason_codes);
    let mut candidates = fs::read_dir(&artifact_dir)
        .ok()?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.is_file())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| {
                    name.contains(&format!("-{}-workflow-pivot-", identity.safe_branch))
                })
        })
        .collect::<Vec<_>>();
    candidates.sort();
    candidates.reverse();

    candidates.into_iter().find(|path| {
        let headers = parse_headers_file(path);
        headers.get("Source Plan") == Some(&format!("`{}`", identity.plan_path))
            && headers.get("Branch") == Some(&identity.branch_name.to_owned())
            && headers.get("Repo") == Some(&identity.repo_slug.to_owned())
            && headers.get("Head SHA") == Some(&identity.head_sha.to_owned())
            && headers.get("Decision Reason Codes") == Some(&decision_reason_codes)
            && headers.get("Generated By") == Some(&String::from(GENERATED_BY))
    })
}

pub(crate) fn write_workflow_pivot_record(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
    reason: &str,
) -> Result<PathBuf, DiagnosticError> {
    let artifact_dir = workflow_pivot_artifact_dir(state_dir, identity.repo_slug);
    fs::create_dir_all(&artifact_dir).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not create workflow pivot artifact directory {}: {error}",
                artifact_dir.display()
            ),
        )
    })?;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let path = artifact_dir.join(format!(
        "{}-{}-workflow-pivot-{timestamp}.md",
        current_user_name(),
        identity.safe_branch
    ));
    let normalized_reason = normalize_reason(reason);
    let decision_reason_codes = render_decision_reason_codes(identity.decision_reason_codes);
    let source = format!(
        "# Workflow Pivot Record\n**Source Plan:** `{}`\n**Branch:** {}\n**Repo:** {}\n**Head SHA:** {}\n**Decision Reason Codes:** {decision_reason_codes}\n**Reason:** {normalized_reason}\n**Generated By:** {GENERATED_BY}\n**Generated At:** {timestamp}\n",
        identity.plan_path, identity.branch_name, identity.repo_slug, identity.head_sha
    );
    fs::write(&path, source).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not write workflow pivot record {}: {error}",
                path.display()
            ),
        )
    })?;
    Ok(path)
}

pub fn record_pivot(
    current_dir: &Path,
    args: &RecordPivotArgs,
) -> Result<WorkflowPivotRecordOutput, DiagnosticError> {
    let slug_identity = discover_slug_identity(current_dir);
    let head_sha = current_head_sha(&slug_identity.repo_root).map_err(|error| {
        DiagnosticError::new(
            FailureClass::BranchDetectionFailed,
            format!(
                "Could not determine the current HEAD commit: {}",
                error.message
            ),
        )
    })?;
    let plan_path = args.plan.to_string_lossy().into_owned();
    let operator = operator(
        current_dir,
        &OperatorArgs {
            plan: args.plan.clone(),
            external_review_result_ready: false,
            json: false,
        },
    )
    .map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not evaluate workflow operator for pivot recording: {}",
                error.message
            ),
        )
    })?;
    if operator.phase != "pivot_required" || operator.phase_detail != "planning_reentry_required" {
        return Ok(WorkflowPivotRecordOutput {
            action: String::from("blocked"),
            plan_path,
            reason: normalize_reason(&args.reason),
            record_path: None,
            remediation: Some(String::from(
                "workflow record-pivot is only valid when workflow/operator routes to pivot_required.",
            )),
        });
    }
    let runtime = ExecutionRuntime::discover(current_dir).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not discover execution runtime for pivot recording: {}",
                error.message
            ),
        )
    })?;
    let context = load_execution_context(&runtime, &args.plan).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not load execution context for pivot recording: {}",
                error.message
            ),
        )
    })?;
    let status = status_from_context(&context).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not load execution status for pivot recording: {}",
                error.message
            ),
        )
    })?;
    let follow_up_requires_pivot = operator.follow_up_override == "record_pivot";
    let qa_requirement_missing_or_invalid = !matches!(
        context.plan_document.qa_requirement.as_deref(),
        Some("required") | Some("not-required")
    );
    let decision_reason_codes = pivot_decision_reason_codes(
        &status.reason_codes,
        follow_up_requires_pivot,
        qa_requirement_missing_or_invalid,
    );
    let identity = WorkflowPivotRecordIdentity {
        repo_slug: &slug_identity.repo_slug,
        safe_branch: &slug_identity.safe_branch,
        plan_path: &plan_path,
        branch_name: &slug_identity.branch_name,
        head_sha: &head_sha,
        decision_reason_codes: &decision_reason_codes,
    };
    let state_dir = featureforge_state_dir();
    let (action, record_path) = if current_workflow_pivot_record_exists(&state_dir, identity) {
        (
            String::from("already_current"),
            latest_matching_workflow_pivot_record(&state_dir, identity).expect(
                "matching workflow pivot record should remain available when existence check passed",
            ),
        )
    } else {
        (
            String::from("recorded"),
            write_workflow_pivot_record(&state_dir, identity, &args.reason)?,
        )
    };

    Ok(WorkflowPivotRecordOutput {
        action,
        plan_path,
        reason: normalize_reason(&args.reason),
        record_path: Some(record_path.display().to_string()),
        remediation: None,
    })
}

pub fn render_pivot_record(output: WorkflowPivotRecordOutput) -> String {
    let mut rendered = format!(
        "Recorded workflow pivot for {}\nReason: {}",
        output.plan_path, output.reason
    );
    if let Some(record_path) = output.record_path {
        rendered.push_str(&format!("\nRecord: {record_path}"));
    }
    rendered
}

pub(crate) fn pivot_decision_reason_codes(
    reason_codes: &[String],
    follow_up_requires_pivot: bool,
    qa_requirement_missing_or_invalid: bool,
) -> Vec<String> {
    let mut reason_codes = reason_codes.to_vec();
    if follow_up_requires_pivot {
        reason_codes.push(String::from("follow_up_override_record_pivot"));
    }
    if qa_requirement_missing_or_invalid {
        reason_codes.push(String::from("qa_requirement_missing_or_invalid"));
    }
    reason_codes.sort();
    reason_codes.dedup();
    reason_codes
}

fn workflow_pivot_artifact_dir(state_dir: &Path, repo_slug: &str) -> PathBuf {
    state_dir.join("projects").join(repo_slug)
}

fn normalize_reason(reason: &str) -> String {
    reason.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn render_decision_reason_codes(reason_codes: &[String]) -> String {
    let mut codes = reason_codes
        .iter()
        .map(|code| code.trim())
        .filter(|code| !code.is_empty())
        .map(str::to_owned)
        .collect::<Vec<_>>();
    codes.sort();
    codes.dedup();
    if codes.is_empty() {
        String::from("none")
    } else {
        codes.join(", ")
    }
}

fn current_user_name() -> String {
    env::var("USER")
        .or_else(|_| env::var("USERNAME"))
        .unwrap_or_else(|_| String::from("user"))
}

fn parse_headers_file(path: &Path) -> BTreeMap<String, String> {
    fs::read_to_string(path)
        .ok()
        .map(|source| parse_headers(&source))
        .unwrap_or_default()
}

fn parse_headers(source: &str) -> BTreeMap<String, String> {
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let rest = line.strip_prefix("**")?;
            let (key, value) = rest.split_once(":** ")?;
            Some((key.to_owned(), value.to_owned()))
        })
        .collect()
}
