use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use schemars::JsonSchema;
use serde::Serialize;

use crate::cli::workflow::{OperatorArgs, RecordPivotArgs};
use crate::diagnostics::{DiagnosticError, FailureClass};
use crate::execution::state::{
    ExecutionRuntime, current_head_sha, load_execution_context_for_exact_plan,
    status_from_context_with_shared_routing,
};
use crate::execution::transitions::{
    load_authoritative_transition_state, read_authoritative_transition_state_source,
};
use crate::git::sha256_hex;
use crate::paths::harness_state_path;
use crate::workflow::operator::operator_for_runtime;

const GENERATED_BY: &str = "featureforge:workflow-record-pivot";

#[derive(Clone, Copy)]
pub(crate) struct WorkflowPivotRecordIdentity<'a> {
    pub repo_slug: &'a str,
    pub safe_branch: &'a str,
    pub plan_path: &'a str,
    pub branch_name: &'a str,
    pub head_sha: &'a str,
    pub decision_reason_codes: &'a [String],
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, JsonSchema)]
pub struct WorkflowPivotRecordOutput {
    pub action: String,
    pub plan_path: String,
    pub reason: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub record_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

pub(crate) fn current_workflow_pivot_record_exists(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> bool {
    current_workflow_pivot_record(state_dir, identity).is_some()
}

fn current_workflow_pivot_record(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> Option<PathBuf> {
    let checkpoint = authoritative_pivot_checkpoint(state_dir, identity)?;
    if !workflow_pivot_record_matches_decision(&checkpoint.path, identity) {
        return None;
    }
    let record_source = fs::read_to_string(&checkpoint.path).ok()?;
    (sha256_hex(record_source.as_bytes()) == checkpoint.fingerprint).then_some(checkpoint.path)
}

pub(crate) fn write_workflow_pivot_record(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
    reason: &str,
) -> Result<(PathBuf, String), DiagnosticError> {
    let artifact_dir = workflow_pivot_artifact_dir(state_dir, identity.repo_slug);
    fs::create_dir_all(&artifact_dir).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not create workflow pivot artifact directory {}: {error}",
                artifact_dir.display()
            ),
        )
    })?;
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let user_name = current_user_name();
    let normalized_reason = normalize_reason(reason);
    let decision_reason_codes = render_decision_reason_codes(identity.decision_reason_codes);
    let source = format!(
        "# Workflow Pivot Record\n**Source Plan:** `{}`\n**Branch:** {}\n**Repo:** {}\n**Head SHA:** {}\n**Decision Reason Codes:** {decision_reason_codes}\n**Reason:** {normalized_reason}\n**Generated By:** {GENERATED_BY}\n**Generated At:** {timestamp}\n",
        identity.plan_path, identity.branch_name, identity.repo_slug, identity.head_sha
    );
    let record_fingerprint = sha256_hex(source.as_bytes());
    loop {
        let path = next_workflow_pivot_record_path(
            &artifact_dir,
            &user_name,
            identity.safe_branch,
            timestamp,
        );
        match fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
        {
            Ok(mut file) => {
                file.write_all(source.as_bytes()).map_err(|error| {
                    DiagnosticError::new(
                        FailureClass::InstructionParseFailed,
                        format!(
                            "Could not write workflow pivot record {}: {error}",
                            path.display()
                        ),
                    )
                })?;
                return Ok((path, record_fingerprint));
            }
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {
                continue;
            }
            Err(error) => {
                return Err(DiagnosticError::new(
                    FailureClass::InstructionParseFailed,
                    format!(
                        "Could not write workflow pivot record {}: {error}",
                        path.display()
                    ),
                ));
            }
        }
    }
}

pub fn record_pivot(
    current_dir: &Path,
    args: &RecordPivotArgs,
) -> Result<WorkflowPivotRecordOutput, DiagnosticError> {
    let runtime = ExecutionRuntime::discover(current_dir).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not discover execution runtime for pivot recording: {}",
                error.message
            ),
        )
    })?;
    record_pivot_for_runtime(&runtime, args)
}

pub fn record_pivot_for_runtime(
    runtime: &ExecutionRuntime,
    args: &RecordPivotArgs,
) -> Result<WorkflowPivotRecordOutput, DiagnosticError> {
    let head_sha = current_head_sha(&runtime.repo_root).map_err(|error| {
        DiagnosticError::new(
            FailureClass::BranchDetectionFailed,
            format!(
                "Could not determine the current HEAD commit: {}",
                error.message
            ),
        )
    })?;
    let context = load_execution_context_for_exact_plan(runtime, &args.plan).map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not load execution context for pivot recording: {}",
                error.message
            ),
        )
    })?;
    let plan_path = context.plan_rel.clone();
    let operator = operator_for_runtime(
        runtime,
        &OperatorArgs {
            plan: args.plan.clone(),
            external_review_result_ready: false,
            json: false,
        },
    )
    .map_err(|error| {
        DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            format!(
                "Could not evaluate workflow operator for pivot recording: {}",
                error.message
            ),
        )
    })?;
    if operator.phase != "pivot_required" || operator.phase_detail != "planning_reentry_required" {
        return Ok(WorkflowPivotRecordOutput {
            action: String::from("blocked"),
            plan_path,
            reason: normalize_reason(&args.reason),
            record_path: None,
            remediation: Some(String::from(
                "workflow record-pivot is only valid when workflow/operator routes to pivot_required.",
            )),
        });
    }
    let status =
        status_from_context_with_shared_routing(runtime, &context, false).map_err(|error| {
            DiagnosticError::new(
                FailureClass::InstructionParseFailed,
                format!(
                    "Could not load execution status for pivot recording: {}",
                    error.message
                ),
            )
        })?;
    let follow_up_requires_pivot =
        operator.phase == "pivot_required" && operator.phase_detail == "planning_reentry_required";
    let qa_requirement_missing_or_invalid = !matches!(
        context.plan_document.qa_requirement.as_deref(),
        Some("required") | Some("not-required")
    );
    let decision_reason_codes = pivot_decision_reason_codes(
        &status.reason_codes,
        follow_up_requires_pivot,
        qa_requirement_missing_or_invalid,
    );
    let identity = WorkflowPivotRecordIdentity {
        repo_slug: &runtime.repo_slug,
        safe_branch: &runtime.safe_branch,
        plan_path: &plan_path,
        branch_name: &runtime.branch_name,
        head_sha: &head_sha,
        decision_reason_codes: &decision_reason_codes,
    };
    let state_dir = runtime.state_dir.clone();
    let (action, record_path, record_fingerprint) =
        if let Some(current_record) = current_workflow_pivot_record(&state_dir, identity) {
            let current_source = fs::read_to_string(&current_record).map_err(|error| {
                DiagnosticError::new(
                    FailureClass::InstructionParseFailed,
                    format!(
                        "Could not read current workflow pivot record {}: {error}",
                        current_record.display()
                    ),
                )
            })?;
            (
                String::from("already_current"),
                current_record,
                sha256_hex(current_source.as_bytes()),
            )
        } else {
            let (record_path, record_fingerprint) =
                write_workflow_pivot_record(&state_dir, identity, &args.reason)?;
            (String::from("recorded"), record_path, record_fingerprint)
        };
    let mut authoritative_state =
        load_authoritative_transition_state(&context).map_err(|error| {
            DiagnosticError::new(
                FailureClass::InstructionParseFailed,
                format!(
                    "Could not load authoritative harness state for pivot recording: {}",
                    error.message
                ),
            )
        })?;
    let Some(authoritative_state) = authoritative_state.as_mut() else {
        return Err(DiagnosticError::new(
            FailureClass::InstructionParseFailed,
            "workflow record-pivot requires authoritative harness state.",
        ));
    };
    authoritative_state
        .record_runtime_pivot_checkpoint(&record_path.display().to_string(), &record_fingerprint)
        .map_err(|error| {
            DiagnosticError::new(
                FailureClass::InstructionParseFailed,
                format!(
                    "Could not persist runtime-owned pivot checkpoint for {}: {}",
                    record_path.display(),
                    error.message
                ),
            )
        })?;
    authoritative_state
        .persist_if_dirty_with_failpoint(None)
        .map_err(|error| {
            DiagnosticError::new(
                FailureClass::InstructionParseFailed,
                format!(
                    "Could not persist authoritative harness state after pivot recording: {}",
                    error.message
                ),
            )
        })?;

    Ok(WorkflowPivotRecordOutput {
        action,
        plan_path,
        reason: normalize_reason(&args.reason),
        record_path: Some(record_path.display().to_string()),
        remediation: None,
    })
}

pub fn render_pivot_record(output: WorkflowPivotRecordOutput) -> String {
    let header = match output.action.as_str() {
        "recorded" => format!("Recorded workflow pivot for {}", output.plan_path),
        "already_current" => format!("Workflow pivot already current for {}", output.plan_path),
        "blocked" => format!("Workflow pivot blocked for {}", output.plan_path),
        action => format!("Workflow pivot {action} for {}", output.plan_path),
    };
    let mut rendered = format!("{header}\nReason: {}", output.reason);
    if let Some(record_path) = output.record_path {
        rendered.push_str(&format!("\nRecord: {record_path}"));
    }
    if let Some(remediation) = output.remediation {
        rendered.push_str(&format!("\nRemediation: {remediation}"));
    }
    rendered
}

pub(crate) fn pivot_decision_reason_codes(
    reason_codes: &[String],
    follow_up_requires_pivot: bool,
    qa_requirement_missing_or_invalid: bool,
) -> Vec<String> {
    let mut reason_codes = reason_codes.to_vec();
    if follow_up_requires_pivot {
        reason_codes.push(String::from("follow_up_override_record_pivot"));
    }
    if qa_requirement_missing_or_invalid {
        reason_codes.push(String::from("qa_requirement_missing_or_invalid"));
    }
    reason_codes.sort();
    reason_codes.dedup();
    reason_codes
}

fn workflow_pivot_artifact_dir(state_dir: &Path, repo_slug: &str) -> PathBuf {
    state_dir.join("projects").join(repo_slug)
}

fn workflow_pivot_record_path(
    artifact_dir: &Path,
    user_name: &str,
    safe_branch: &str,
    timestamp: u64,
    suffix: u32,
) -> PathBuf {
    let file_name = if suffix == 0 {
        format!("{user_name}-{safe_branch}-workflow-pivot-{timestamp}.md")
    } else {
        format!("{user_name}-{safe_branch}-workflow-pivot-{timestamp}-{suffix}.md")
    };
    artifact_dir.join(file_name)
}

pub(crate) fn next_workflow_pivot_record_path(
    artifact_dir: &Path,
    user_name: &str,
    safe_branch: &str,
    timestamp: u64,
) -> PathBuf {
    let mut suffix = 0_u32;
    loop {
        let candidate =
            workflow_pivot_record_path(artifact_dir, user_name, safe_branch, timestamp, suffix);
        if !candidate.exists() {
            return candidate;
        }
        suffix = suffix.saturating_add(1);
    }
}

fn normalize_reason(reason: &str) -> String {
    reason.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn render_decision_reason_codes(reason_codes: &[String]) -> String {
    let mut codes = reason_codes
        .iter()
        .map(|code| code.trim())
        .filter(|code| !code.is_empty())
        .map(str::to_owned)
        .collect::<Vec<_>>();
    codes.sort();
    codes.dedup();
    if codes.is_empty() {
        String::from("none")
    } else {
        codes.join(", ")
    }
}

struct PivotCheckpoint {
    path: PathBuf,
    fingerprint: String,
}

fn authoritative_pivot_checkpoint(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> Option<PivotCheckpoint> {
    let state_path = harness_state_path(state_dir, identity.repo_slug, identity.branch_name);
    let source = read_authoritative_transition_state_source(&state_path)
        .ok()
        .flatten()?;
    let payload: serde_json::Value = serde_json::from_str(&source).ok()?;
    let root = payload.as_object()?;
    let path = root
        .get("last_pivot_path")
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())?;
    let fingerprint = root
        .get("last_pivot_fingerprint")
        .and_then(serde_json::Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())?;
    let path = PathBuf::from(path);
    if !trusted_pivot_checkpoint_path(state_dir, identity, &path) {
        return None;
    }
    Some(PivotCheckpoint {
        path: fs::canonicalize(path).ok()?,
        fingerprint: fingerprint.to_owned(),
    })
}

fn trusted_pivot_checkpoint_path(
    state_dir: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
    path: &Path,
) -> bool {
    let canonical_path = match fs::canonicalize(path) {
        Ok(path) => path,
        Err(_) => return false,
    };
    let canonical_artifact_dir =
        match fs::canonicalize(workflow_pivot_artifact_dir(state_dir, identity.repo_slug)) {
            Ok(path) => path,
            Err(_) => return false,
        };
    if !canonical_path.starts_with(canonical_artifact_dir) {
        return false;
    }
    let Some(file_name) = canonical_path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    file_name.contains(&format!("-{}-workflow-pivot-", identity.safe_branch))
        && file_name.ends_with(".md")
}

fn workflow_pivot_record_matches_decision(
    path: &Path,
    identity: WorkflowPivotRecordIdentity<'_>,
) -> bool {
    let headers = parse_headers_file(path);
    let decision_reason_codes = render_decision_reason_codes(identity.decision_reason_codes);
    headers.get("Source Plan") == Some(&format!("`{}`", identity.plan_path))
        && headers.get("Branch") == Some(&identity.branch_name.to_owned())
        && headers.get("Repo") == Some(&identity.repo_slug.to_owned())
        && headers.get("Head SHA") == Some(&identity.head_sha.to_owned())
        && headers.get("Decision Reason Codes") == Some(&decision_reason_codes)
        && headers.get("Generated By") == Some(&String::from(GENERATED_BY))
}

fn current_user_name() -> String {
    env::var("USER")
        .or_else(|_| env::var("USERNAME"))
        .unwrap_or_else(|_| String::from("user"))
}

fn parse_headers_file(path: &Path) -> BTreeMap<String, String> {
    fs::read_to_string(path)
        .ok()
        .map(|source| parse_headers(&source))
        .unwrap_or_default()
}

fn parse_headers(source: &str) -> BTreeMap<String, String> {
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            let rest = line.strip_prefix("**")?;
            let (key, value) = rest.split_once(":** ")?;
            Some((key.to_owned(), value.to_owned()))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{WorkflowPivotRecordOutput, next_workflow_pivot_record_path, render_pivot_record};
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn render_pivot_record_text_reflects_recorded_action() {
        let rendered = render_pivot_record(WorkflowPivotRecordOutput {
            action: String::from("recorded"),
            plan_path: String::from("docs/featureforge/plans/example.md"),
            reason: String::from("plan drift"),
            record_path: Some(String::from("/tmp/pivot.md")),
            remediation: None,
        });
        assert!(rendered.contains("Recorded workflow pivot for"));
        assert!(rendered.contains("Reason: plan drift"));
        assert!(rendered.contains("Record: /tmp/pivot.md"));
    }

    #[test]
    fn render_pivot_record_text_reflects_already_current_action() {
        let rendered = render_pivot_record(WorkflowPivotRecordOutput {
            action: String::from("already_current"),
            plan_path: String::from("docs/featureforge/plans/example.md"),
            reason: String::from("plan drift"),
            record_path: Some(String::from("/tmp/pivot.md")),
            remediation: None,
        });
        assert!(rendered.starts_with("Workflow pivot already current for"));
    }

    #[test]
    fn render_pivot_record_text_reflects_blocked_action_with_remediation() {
        let rendered = render_pivot_record(WorkflowPivotRecordOutput {
            action: String::from("blocked"),
            plan_path: String::from("docs/featureforge/plans/example.md"),
            reason: String::from("plan drift"),
            record_path: None,
            remediation: Some(String::from(
                "workflow record-pivot is only valid when workflow/operator routes to pivot_required.",
            )),
        });
        assert!(rendered.starts_with("Workflow pivot blocked for"));
        assert!(rendered.contains("Reason: plan drift"));
        assert!(rendered.contains("Remediation: workflow record-pivot is only valid"));
    }

    #[test]
    fn next_workflow_pivot_record_path_avoids_same_second_clobbering() {
        let tempdir = TempDir::new().expect("tempdir should exist");
        let artifact_dir = tempdir.path();
        let first = artifact_dir.join("user-feature-workflow-pivot-123.md");
        fs::write(&first, "existing").expect("existing pivot record should be writable");

        let next = next_workflow_pivot_record_path(artifact_dir, "user", "feature", 123);
        assert_eq!(
            next.file_name().and_then(|name| name.to_str()),
            Some("user-feature-workflow-pivot-123-1.md")
        );

        fs::write(&next, "next").expect("next pivot record should be writable");
        let third = next_workflow_pivot_record_path(artifact_dir, "user", "feature", 123);
        assert_eq!(
            third.file_name().and_then(|name| name.to_str()),
            Some("user-feature-workflow-pivot-123-2.md")
        );
    }
}
